### ISSUE TITLE
Unhandled exception (dDslWnV)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#328] opened 2018-01-03 04:21 UTC
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/root/zeus-scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/zeus-scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/root/zeus-scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
WebDriverException: Message: Service /usr/bin/geckodriver unexpectedly exited. Status code was: 101
```

Running details:
`Linux-2.6.32-042stab125.3-x86_64-with-debian-buster-sid`

Commands used:
`/root/zeus-scanner/zeus.py -d inurl:ticker.cfm?action= -L 100 --proxy=socks4://127.0.0.1:16927`

Log file info:
```2018-01-03 07:21:31,075;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-153.log'
2018-01-03 07:21:31,077;zeus-log;WARNING;timeout will be increased to 40s due to Tor being used
2018-01-03 07:21:31,077;zeus-log;INFO;using default search engine
2018-01-03 07:21:31,077;zeus-log;INFO;starting dork scan with query 'inurl:ticker.cfm?action='
2018-01-03 07:21:31,079;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)
2018-01-03 07:21:31,079;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
2018-01-03 07:21:31,079;zeus-log;INFO;attempting to gather query URL
2018-01-03 07:21:31,082;zeus-log;INFO;setting up virtual display to hide the browser
2018-01-03 07:21:31,286;zeus-log;INFO;setting the browser
2018-01-03 07:21:34,852;zeus-log;ERROR;[7;31;31mselenium_search.pyc failed to gather the URL from search engine, caught exception 'Message: Service /usr/bin/geckodriver unexpectedly exited. Status code was: 101' exception has been logged to current log file
Traceback (most recent call last):
  File "/root/zeus-scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/zeus-scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/root/zeus-scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
WebDriverException: Message: Service /usr/bin/geckodriver unexpectedly exited. Status code was: 101


2018-01-03 07:21:38,396;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2018-01-03 07:21:38,396;zeus-log;INFO;[32mgetting authorization[0m
2018-01-03 07:21:38,397;zeus-log;INFO;[32mextracting traceback from log file[0m
2018-01-03 07:21:38,397;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2018-01-03 04:23
Your proxy is bad, change it

**Comment by Ekultek** [comment] 2018-01-03 18:56
Duplicate of #327

**Closed by Ekultek** 2018-01-03 18:56 UTC
