### ISSUE TITLE
Unhandled exception (PxsmZfD)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#209] opened 2017-12-01 18:31 UTC
Zeus version:
`1.3.11.083e54`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 998, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 261, in main
    check_for_admin_page(url, extensions, show_possibles=show, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 140, in check_for_admin_page
    if int(data[2].split(":")[0]) == error_code:
ValueError: invalid literal for int() with base 10: '400:'
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:admin.php --verbose --batch -a --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -W -E`

Log file info:
```2017-12-01 12:30:40,762;zeus-log;INFO;random IP address generated for header '80.109.167.99'...
2017-12-01 12:30:40,762;zeus-log;INFO;random IP address generated for header '109.47.124.186'...
2017-12-01 12:30:40,763;zeus-log;INFO;random IP address generated for header '0.20.157.16'...
2017-12-01 12:30:40,827;zeus-log;ERROR;unable to retrieve headers for site 'https://core.trac.wordpress.'...
2017-12-01 12:30:40,828;zeus-log;INFO;parsing robots.txt...
2017-12-01 12:30:41,028;zeus-log;INFO;robots.txt page will be saved into a file...
2017-12-01 12:30:41,028;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/robots/core.trac.wordpress.-robots_text.log'...
2017-12-01 12:30:41,028;zeus-log;INFO;checking for a sitemap...
2017-12-01 12:30:41,233;zeus-log;INFO;found a sitemap, saving to file...
2017-12-01 12:30:41,233;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/sitemap-log/core.trac.wordpress.-sitemap.xml'...
2017-12-01 12:30:41,233;zeus-log;INFO;loading extensions...
2017-12-01 12:30:41,288;zeus-log;DEBUG;loaded a total of 643 extensions...
2017-12-01 12:30:41,288;zeus-log;INFO;attempting to bruteforce admin panel...
2017-12-01 12:30:41,288;zeus-log;DEBUG;trying 'http://core.trac.wordpress.:23'...
2017-12-01 12:30:46,319;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:30:46,320;zeus-log;DEBUG;trying 'http://core.trac.wordpress.:82'...
2017-12-01 12:30:51,383;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:30:51,383;zeus-log;DEBUG;trying 'http://core.trac.wordpress.:2082'...
2017-12-01 12:30:56,459;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:30:56,460;zeus-log;DEBUG;trying 'http://core.trac.wordpress.:2083'...
2017-12-01 12:31:01,486;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:31:01,487;zeus-log;DEBUG;trying 'http://core.trac.wordpress./administratie/'...
2017-12-01 12:31:01,668;zeus-log;INFO;connected successfully to 'http://core.trac.wordpress./administratie/'...
2017-12-01 12:31:01,669;zeus-log;DEBUG;trying 'http://core.trac.wordpress./admin/voucher.php'...
2017-12-01 12:31:01,848;zeus-log;INFO;connected successfully to 'http://core.trac.wordpress./admin/voucher.php'...
2017-12-01 12:31:01,849;zeus-log;DEBUG;trying 'http://core.trac.wordpress./yonetim.asp'...
2017-12-01 12:31:02,037;zeus-log;INFO;connected successfully to 'http://core.trac.wordpress./yonetim.asp'...
2017-12-01 12:31:02,038;zeus-log;DEBUG;trying 'http://core.trac.wordpress./useradmin/'...
2017-12-01 12:31:02,222;zeus-log;INFO;connected successfully to 'http://core.trac.wordpress./useradmin/'...
2017-12-01 12:31:02,223;zeus-log;DEBUG;trying 'http://core.trac.wordpress./relogin.htm'...
2017-12-01 12:31:02,441;zeus-log;INFO;connected successfully to 'http://core.trac.wordpress./relogin.htm'...
2017-12-01 12:31:02,441;zeus-log;DEBUG;trying 'http://core.trac.wordpress./super%EXT%'...
2017-12-01 12:31:02,629;zeus-log;ERROR;[7;31;31mran into exception 'invalid literal for int() with base 10: '400:'' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 998, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 261, in main
    check_for_admin_page(url, extensions, show_possibles=show, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 140, in check_for_admin_page
    if int(data[2].split(":")[0]) == error_code:
ValueError: invalid literal for int() with base 10: '400:'

2017-12-01 12:31:02,890;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-01 12:31:02,890;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-01 12:31:02,911;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-01 12:31:02,911;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-12-01 18:44
duplicate of #207

**Closed by Ekultek** 2017-12-01 18:44 UTC
Labels: duplicate
