### ISSUE TITLE
Unhandled exception (mwqDLoq)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#272] opened 2017-12-07 05:38 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Network Camera NetworkCamera" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:38:35,689;zeus-log;DEBUG;loading script 'jquery'
2017-12-06 23:38:35,690;zeus-log;DEBUG;loading script 'clipbucket'
2017-12-06 23:38:35,691;zeus-log;DEBUG;loading script 'ihtml'
2017-12-06 23:38:35,691;zeus-log;DEBUG;loading script '360'
2017-12-06 23:38:35,692;zeus-log;DEBUG;loading script '3dcart'
2017-12-06 23:38:35,692;zeus-log;DEBUG;loading script 'b2evolution'
2017-12-06 23:38:35,693;zeus-log;DEBUG;loading script 'bmcremedy'
2017-12-06 23:38:35,695;zeus-log;DEBUG;loading script 'abyss'
2017-12-06 23:38:35,695;zeus-log;DEBUG;loading script '68classified'
2017-12-06 23:38:35,696;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:38:35,696;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:38:35,697;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:38:35,697;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:38:35,698;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:38:35,699;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:38:35,699;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:38:35,700;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:38:35,701;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:38:35,701;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:38:35,702;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:38:35,703;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:38:35,703;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:38:35,704;zeus-log;WARNING;no known plugins identified on target
2017-12-06 23:38:35,704;zeus-log;DEBUG;loading XML data
2017-12-06 23:38:35,705;zeus-log;INFO;attempting to get request headers for 'http://www.vstarcam.com/Wireless-Indoor-IP-Camera-27.html'
2017-12-06 23:38:35,705;zeus-log;DEBUG;fetched {'Content-Length': '232', 'Keep-Alive': 'timeout=5, max=100', 'Server': 'Apache/2.2.9 (Unix) PHP/5.2.6', 'Connection': 'Keep-Alive', 'Date': 'Thu, 07 Dec 2017 05:38:35 GMT', 'Content-Type': 'text/html; charset=iso-8859-1'}
2017-12-06 23:38:35,706;zeus-log;INFO;writing found headers to log file
2017-12-06 23:38:35,706;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.vstarcam.com-headers.json'
2017-12-06 23:38:35,707;zeus-log;INFO;searching a total of 5 pages of Gists for 'www.vstarcam.com'
2017-12-06 23:38:35,707;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:38:36,237;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:38:36,740;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:38:37,258;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:38:37,808;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:38:38,359;zeus-log;DEBUG;found a total of 53 links to search
2017-12-06 23:38:39,029;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rajegannathan/222d72698580c2e9b2bdbf2cc887c12d/raw/badbb7146de1bb73a72af49a14f6bbec9bbd9d65/racist-ai.ipynb'
2017-12-06 23:38:39,990;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/debashisbarman/f2a708ff8fb8e9a68463ea014e73b062/raw/6553c03d8632dfe021114e74019e7f4dd3e93849/package.json'
2017-12-06 23:38:41,272;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/d14a2f9a72c2d721745992b56bc53d11/raw/6569bf2cfbe63f7dd7de177f1bc042754288e52b/brlog.trunk-test.20171207-142233'
2017-12-06 23:38:42,542;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/499940e908907614cff8f076937be6c2/raw/42294004b447d32f843d6ebd11f5d89dc6a95489/brlog.trunk-test.20171207-143132'
2017-12-06 23:38:43,748;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/eb5258165c582ded1c8328438e4b7f6b/raw/059a54383f2781763f91892b690ac8bb0f08eb1a/brlog.trunk-test.20171207-143100'
2017-12-06 23:38:45,195;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:38:45,317;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:38:45,317;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:38:45,318;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:38:45,318;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:22
duplicate of #256

**Closed** 2017-12-07 13:22 UTC
Labels: duplicate
