### ISSUE TITLE
Unhandled exception (DumWgUp)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#264] opened 2017-12-07 05:28 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle: "index of/root" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:28:02,112;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:28:02,113;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:28:02,114;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:28:02,115;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:28:02,117;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:28:02,118;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:28:02,125;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:28:02,126;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:28:02,127;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:28:02,133;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:28:02,134;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:28:02,135;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:28:02,136;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:28:02,137;zeus-log;INFO;possible plugin identified as 'JQuery'
2017-12-06 23:28:02,138;zeus-log;DEBUG;loading XML data
2017-12-06 23:28:02,138;zeus-log;INFO;attempting to get request headers for 'http://search.proquest.com/openview/d0bfd81460b019f16b39caa95601c281/1?pq-origsite=gscholar&cbl=33690'
2017-12-06 23:28:02,139;zeus-log;INFO;found a request cookie, saving to file
2017-12-06 23:28:02,139;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/search.proquest.com-cookie.log'
2017-12-06 23:28:02,140;zeus-log;DEBUG;fetched {'Content-Length': '4370', 'Content-Encoding': 'gzip', 'Set-Cookie': 'JSESSIONID=B422EB1041A6AD5EADB89DD9C233FE57.i-0fc6c37e33c170b0e; Path=/; Secure, AWSELB=D5FDE137081236662C1E03C79BDE028E4ACADE6ABDF818C6564D5C3ACBFC65554E4205432C882EC7261C23B6E7E8494F56A721CB44D196EABF1AF2BC315BDE5B7734A7599F0CE342CE688C6ED764D4105147A92780;PATH=/;SECURE, availability-zone=us-east-1c;Path=/', 'Strict-Transport-Security': 'max-age=1576800', 'Vary': 'Accept-Encoding', 'Connection': 'keep-alive', 'Date': 'Thu, 07 Dec 2017 05:28:00 GMT', 'Content-Type': 'text/html;charset=UTF-8'}
2017-12-06 23:28:02,140;zeus-log;WARNING;provided target has protection against unencrypted connections (force HTTPS connection)
2017-12-06 23:28:02,140;zeus-log;INFO;writing found headers to log file
2017-12-06 23:28:02,140;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/search.proquest.com-headers.json'
2017-12-06 23:28:02,141;zeus-log;INFO;searching a total of 5 pages of Gists for 'search.proquest.com'
2017-12-06 23:28:02,141;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:28:02,710;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:28:03,261;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:28:04,121;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:28:04,760;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:28:05,262;zeus-log;DEBUG;found a total of 53 links to search
2017-12-06 23:28:05,886;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/x831617/3d434d22bad00b4aa6f89dd057006fe4/raw/6106e4bb52e6cf2e903851c2d5923f0465518852/gistfile1.txt'
2017-12-06 23:28:07,142;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/40536a74787c6c67119faa45220fe123/raw/5d6baf4c1a2f890bea59b1381a80bb662ff46931/brlog.trunk-test.20171207-142138'
2017-12-06 23:28:08,220;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/theatlasroom/b09c9ef74aec56858383a11b28b3f8df/raw/239b238f870c10dbb54027bbe2bbb9b2c545ebaf/glossing-over-ethereum.md'
2017-12-06 23:28:09,278;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/wynot/0889755e08ab42e2394f205aaa47c58e/raw/c3d39585aec8cc8caf7a990e49cacb3f5235b1e9/gistfile1.txt'
2017-12-06 23:28:10,488;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/bb98542f524d307378eb1327e23ceb6c/raw/80b9fbce9daa43d71a75187f62665db90b10c135/brlog.trunk-test.20171207-141639'
2017-12-06 23:28:13,667;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/nitinware/e611ff7caf61ddf62c6652c359df83e1/raw/a9df894b278261c426ce889854ec719e3e2923f8/temperature.json'
2017-12-06 23:28:14,835;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/yambal/e3225e09e4ee682649d2e025f4326d21/raw/aacf3f072ab45fed5021ea3c0b413899e91b6214/QuickRelux_long.ssml'
2017-12-06 23:28:16,000;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/81b9e8b51b34f729b6957d96812dce6e/raw/775fb73394951aea5bf8c74e6b1089235c6a39d5/brlog.trunk-test.20171207-141653'
2017-12-06 23:28:17,168;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/9fdb2a59ae754ccafbfa60eb42f5e4d5/raw/52f8b3e0e8d2d90d70f2c5df8bad6d7fd49822e4/brlog.trunk-test.20171207-141404'
2017-12-06 23:28:18,526;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/189c1d7c650564d04d42ee4f5316062f/raw/943a323617efa0932571330a19a71848ccfd30a3/brlog.trunk-test.20171207-142406'
2017-12-06 23:28:19,961;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/4f0a2cff9daa58772a7887351462baa5/raw/7905f04057048228e2a936631a7932d650c70ac2/brlog.trunk-test.20171207-141413'
2017-12-06 23:28:21,407;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:28:21,536;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:28:21,536;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:28:21,537;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:28:21,538;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:19
duplicate of #256

**Closed** 2017-12-07 13:20 UTC
Labels: duplicate
