### ISSUE TITLE
Unhandled exception (QbnFljX)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#271] opened 2017-12-07 05:38 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Network Camera NetworkCamera" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:38:10,043;zeus-log;DEBUG;loading script '360'
2017-12-06 23:38:10,058;zeus-log;DEBUG;loading script '3dcart'
2017-12-06 23:38:10,067;zeus-log;DEBUG;loading script 'b2evolution'
2017-12-06 23:38:10,091;zeus-log;DEBUG;loading script 'bmcremedy'
2017-12-06 23:38:10,092;zeus-log;DEBUG;loading script 'abyss'
2017-12-06 23:38:10,093;zeus-log;DEBUG;loading script '68classified'
2017-12-06 23:38:10,107;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:38:10,123;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:38:10,133;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:38:10,160;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:38:10,174;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:38:10,188;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:38:16,601;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:38:16,620;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:38:16,636;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:38:23,026;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:38:23,027;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:38:23,037;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:38:23,051;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:38:23,066;zeus-log;WARNING;no known plugins identified on target
2017-12-06 23:38:23,066;zeus-log;DEBUG;loading XML data
2017-12-06 23:38:23,067;zeus-log;INFO;attempting to get request headers for 'https://www.alibaba.com/showroom/network-camera-networkcamera.html'
2017-12-06 23:38:23,067;zeus-log;INFO;found a request cookie, saving to file
2017-12-06 23:38:23,068;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.alibaba.com-cookie.log'
2017-12-06 23:38:23,068;zeus-log;DEBUG;fetched {'Content-Language': 'en-US', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'ali_apache_id=72.198.49.179.1512625089249.459188.2; path=/; domain=.alibaba.com; expires=Wed, 30-Nov-2084 01:01:01 GMT, JSESSIONID=EF6Y58ISO2-BLOQ6DVIPFGC6OJNHZRX1-QQ8X1WAJ-1SV5; Path=/; HttpOnly, ali_apache_track=; Domain=.alibaba.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, ali_apache_tracktmp=; Domain=.alibaba.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, xman_us_f=x_l=0; Domain=.alibaba.com; Expires=Tue, 25-Dec-2085 08:52:16 GMT; Path=/, acs_usuc_t=acs_rt=595e86f77b13481799ff4c669c63d20b; Domain=.alibaba.com; Path=/, xman_t=6GvNmGzaF3647G/PWBkOvIvAnvhs7VjECWrRRD/40MJHvSMKx3kREaAm/Gp9e8HE; Domain=.alibaba.com; Path=/; HttpOnly, xman_f=4U4cy2yRwdZTdutxTTyGl/EVbCda+JtuhHWW+qG/C3n4gudfbmQoAJq4G1IxQ8pJ/bK6mF+9Q549UHC4itO7ctEDwIsskwSn/v90beopdKMgmY8WZGqcMg==; Domain=.alibaba.com; Expires=Tue, 25-Dec-2085 08:52:16 GMT; Path=/; HttpOnly, _mle_tmp0=eNrz4A12DQ729PeL9%2FV3cfUxiKnOTLFScnUzizS18Az2N9J18vEPNHMJ8wxwc3c28%2Ffy84gKijDUDQy0iDAMd%2FTSNQwOM1XSSS6xMjQ1NDIzMjWwsDQxNNBJTEYTyK2wMqiNAgCDoh0N; Path=/; HttpOnly', 'Strict-Transport-Security': 'max-age=31536000', 'Vary': 'Accept-Encoding', 'Server': 'Apache-Coyote/1.1', 'Connection': 'keep-alive', 'Resin-Trace': 'ali_resin_trace=is_merge_supplier=0|ser=1007|pageId=418d529895fa418aa4c273ecf77730f7|set=3|is_escrow_filt=0|sn_cat_type=2|is_onsite_check=0|intro_help_disp=1|is_gs_filt=0|proxy_ip=0|searchweb_vm_style_group=new_version|beaconId=595e86f77b13481799ff4c669c63d20b|pvmi=a68a98ae41484990817b9bbe2135a400|is_av_filt=0|sek_sepd=network+camera+networkcamera|is_as_filt=0|is_f0_test=1|industry_id=301102|bran_ab_test=0|sq_type=a|isAtmOnline=0|kw_type=0|semi=0|se_rst=42|isGalleryList=1|se_pn=1|forecast_post_cate=301102:0:255|is_chinasuppliers=0|s_abtest=01_M_R|p4pid=71e62b50-d2aa-4e00-a006-050e24ff7ac7|sek=network+camera+networkcamera', 'Date': 'Thu, 07 Dec 2017 05:38:09 GMT', 'P3P': 'CP="CAO PSA OUR"', 'Content-Type': 'text/html;charset=UTF-8'}
2017-12-06 23:38:23,069;zeus-log;WARNING;provided target has protection against unencrypted connections (force HTTPS connection)
2017-12-06 23:38:23,069;zeus-log;INFO;writing found headers to log file
2017-12-06 23:38:23,069;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.alibaba.com-headers.json'
2017-12-06 23:38:23,070;zeus-log;INFO;searching a total of 5 pages of Gists for 'www.alibaba.com'
2017-12-06 23:38:23,070;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:38:23,581;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:38:24,103;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:38:24,602;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:38:25,118;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:38:25,676;zeus-log;DEBUG;found a total of 53 links to search
2017-12-06 23:38:26,295;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rajegannathan/222d72698580c2e9b2bdbf2cc887c12d/raw/badbb7146de1bb73a72af49a14f6bbec9bbd9d65/racist-ai.ipynb'
2017-12-06 23:38:27,342;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/debashisbarman/f2a708ff8fb8e9a68463ea014e73b062/raw/6553c03d8632dfe021114e74019e7f4dd3e93849/package.json'
2017-12-06 23:38:28,678;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/d14a2f9a72c2d721745992b56bc53d11/raw/6569bf2cfbe63f7dd7de177f1bc042754288e52b/brlog.trunk-test.20171207-142233'
2017-12-06 23:38:29,964;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/499940e908907614cff8f076937be6c2/raw/42294004b447d32f843d6ebd11f5d89dc6a95489/brlog.trunk-test.20171207-143132'
2017-12-06 23:38:31,405;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/eb5258165c582ded1c8328438e4b7f6b/raw/059a54383f2781763f91892b690ac8bb0f08eb1a/brlog.trunk-test.20171207-143100'
2017-12-06 23:38:32,974;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:38:33,115;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:38:33,115;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:38:33,116;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:38:33,117;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:22
duplicate of #256

**Closed** 2017-12-07 13:22 UTC
Labels: duplicate
