### ISSUE TITLE
Unhandled exception (WZkEzRd)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#172] opened 2017-11-27 14:45 UTC
Zeus version:
`1.2.38`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/root/Documents/Zeus-Scanner/Zeus-Scanner/var/blackwidow/__init__.py", line 59, in test_connection
    self.url, attempt.status_code
SpiderTestFailure: failed to connect to 'http://help.pointforce.com/', received status code: 500
````

Running details:
`Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py -b http://help.pointforce.com/`

Log file info:
```2017-11-27 09:45:18,759;zeus-log;INFO;log file being saved to '/root/Documents/Zeus-Scanner/Zeus-Scanner/log/zeus-log-10.log'...
2017-11-27 09:45:18,759;zeus-log;INFO;using default search engine...
2017-11-27 09:45:18,759;zeus-log;INFO;starting blackwidow on 'http://help.pointforce.com/'...
2017-11-27 09:45:18,774;zeus-log;ERROR;[7;31;31mfailed to connect to 'http://help.pointforce.com/' received error 'failed to connect to 'http://help.pointforce.com/', received status code: 500'...
Traceback (most recent call last):
  File "/root/Documents/Zeus-Scanner/Zeus-Scanner/var/blackwidow/__init__.py", line 59, in test_connection
    self.url, attempt.status_code
SpiderTestFailure: failed to connect to 'http://help.pointforce.com/', received status code: 500

2017-11-27 09:45:32,761;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-27 09:45:32,761;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-27 09:45:32,761;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-27 09:45:32,761;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-11-27 15:56
duplicate of #171

**Closed by Ekultek** 2017-11-27 15:56 UTC
Labels: duplicate
