### ISSUE TITLE
Unhandled exception (d30b2195)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#367] opened 2018-03-17 15:19 UTC
Zeus version:
`1.5.2.55ba7c`

Firefox version:
`failed to start`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/root/Desktop/zeus-scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/Desktop/zeus-scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/root/Desktop/zeus-scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Failed to start browser /usr/bin/firefox: no such file or directory
```

Running details:
`Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py -l /root/Desktop/dorks.txt`

Log file info:
```2018-03-17 11:18:59,258;zeus-log;INFO;log file being saved to '/root/Desktop/zeus-scanner/log/zeus-log-16.log'
2018-03-17 11:18:59,258;zeus-log;INFO;using default search engine
2018-03-17 11:18:59,260;zeus-log;INFO;starting dork scan with query '.php?id= milf'
2018-03-17 11:18:59,260;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)
2018-03-17 11:18:59,260;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
2018-03-17 11:18:59,260;zeus-log;INFO;attempting to gather query URL
2018-03-17 11:18:59,260;zeus-log;INFO;setting up virtual display to hide the browser
2018-03-17 11:18:59,403;zeus-log;INFO;setting the browser
2018-03-17 11:19:02,369;zeus-log;ERROR;[7;31;31mselenium_search.pyc failed to gather the URL from search engine, caught exception 'Message: Failed to start browser /usr/bin/firefox: no such file or directory' exception has been logged to current log file
Traceback (most recent call last):
  File "/root/Desktop/zeus-scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/Desktop/zeus-scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/root/Desktop/zeus-scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Failed to start browser /usr/bin/firefox: no such file or directory


2018-03-17 11:19:02,453;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2018-03-17 11:19:02,454;zeus-log;INFO;[32mgetting authorization[0m
2018-03-17 11:19:02,454;zeus-log;INFO;[32mextracting traceback from log file[0m
2018-03-17 11:19:02,454;zeus-log;INFO;[32mattempting to get firefox browser version[0m
2018-03-17 11:19:02,458;zeus-log;ERROR;[7;31;31mfailed to run firefox[0m
```

**Comment by Ekultek** [comment] 2018-03-19 00:21
Dupe of #366

**Closed by Ekultek** 2018-03-19 00:21 UTC
Labels: duplicate
