### ISSUE TITLE
Unhandled exception (rvRUGdC)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#260] opened 2017-12-07 05:26 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle: "index of/root" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:26:09,310;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/186321c971d0465f5e4f64072bc56aab/raw/46646d48f974030638ad974c6d029b55e4fb4425/brlog.trunk-asserts-nopara.20171207-134231'
2017-12-06 23:26:11,081;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/luannguyen252/fb369d3d4722f784d4646eca5729f714/raw/a51ecf66d7c4e430873a219d954f24a1bc98b27a/01-gulpfile.js'
2017-12-06 23:26:12,350;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/e7ea250d224a2984f118dd8abfb20cc9/raw/2d72c1a8f6a17af4b8415592e586999c2fca3c0f/brlog.trunk-test.20171207-142637'
2017-12-06 23:26:13,617;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/fabiovella83/a3bbb8ade758a398a12389a98523ebab/raw/239b238f870c10dbb54027bbe2bbb9b2c545ebaf/glossing-over-ethereum.md'
2017-12-06 23:26:14,998;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/gdi2290/d7b91aff22b72bc984b29a5cbfb931db/raw/d64e79b0954e6803cfc03cfa1603402c072164f6/lambda-edge.js'
2017-12-06 23:26:15,887;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/atakori/e80fa30ee6de0525979d214d67cac614/raw/81a5858fc8a9b389bf90973c00b88fd492fa5c86/Drills.doc'
2017-12-06 23:26:17,165;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/d14a2f9a72c2d721745992b56bc53d11/raw/6569bf2cfbe63f7dd7de177f1bc042754288e52b/brlog.trunk-test.20171207-142233'
2017-12-06 23:26:18,485;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/cwitch1/0cf2a217e39adc98b5a32d328a0bd652/raw/e14499deaacdfcc3e6835b0efae8c501c78928ac/Prac%2520Fin%25202.cpp'
2017-12-06 23:26:19,414;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ntchambers/f589e75436e9126c9323b00b860267b0/raw/d2f19c213c828de06d241eeeb2b1766f0e076f54/mem.cpp'
2017-12-06 23:26:20,680;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/3fd09200ed746dc41f71ed67e225d29a/raw/982a2097e9b2e554481a6e492600585dc635ad8f/brlog.trunk-test.20171207-141146'
2017-12-06 23:26:21,712;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/igoldin74/67097fcbfdcdd31b3761d2c1d40372be/raw/b442592a713140b1b8a4e42742f1151355fcef0f/gistfile1.txt'
2017-12-06 23:26:22,656;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/dustinlacewell-wk/54c7591fde643d12e5d7bb0571decfd1/raw/9972504b5fb63aad74b6cfebd99a9eeb429d7427/1.fs'
2017-12-06 23:26:23,642;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/pydsigner/2e2312e6e53ddadcbcc6e3834ac80d31/raw/f81132e5e5ac7282203c5616a7abf11797557e66/d07_dirty.py'
2017-12-06 23:26:25,003;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/HenryFBP/8aa8fb091824b01e37d54dc30b1d6f6e/raw/bee1030151c543e324eaad886ac1f3c827936e5f/all_lock_c.js'
2017-12-06 23:26:26,175;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/095714c16f956c8f1d69632c7a7c9565/raw/54d54859b14c50562c1cf0f6bb9c4513fc678930/brlog.trunk-test.20171207-140822'
2017-12-06 23:26:27,226;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/MariaJackson1/882a66af4e157f67f54ccbb833e83cee/raw/aa50d6198149fcab5dc1003d9214ac1c67d0edf5/Remove%2520Additional%2520CSS%2520Setting%2520in%2520WordPress%2520Customizer'
2017-12-06 23:26:28,236;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/tatsushitoji/3c15a626aa3039cc8ad1d603e8c1db62/raw/f4631ecc27a083006fb212956276574188ba9a57/easing.sass'
2017-12-06 23:26:29,361;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/qsLI/ccd136dbe0dcc2fd382a626662add8fc/raw/ebffd264f5022c69f86d15a44c9d0f634642bec4/memcached.sh'
2017-12-06 23:26:30,398;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/romyilano/1b1768fed55c781deaf5e8fd08ee21e2/raw/0f63470005bec0cb6f8e6f7cd709e17b71e6a896/reade.md'
2017-12-06 23:26:32,082;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/d5e3f4fea6778f7a55e61ef9644de9da/raw/b38a2fb10426cbe4594f86c8f0dcd9f4b437fb42/brlog.trunk-test.20171207-141910'
2017-12-06 23:26:33,265;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/kjunichi/55cbcd0d34d23c2e65039e690cbd5dae/raw/b14084cebe6c1d69718c1a176634423a99750a0d/20171207.md'
2017-12-06 23:26:34,318;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/yukw777/0948e90d3d9ae0b8c7ad212794028aba/raw/05d7dfa61a3e3555d8677f77d4be828730f08579/game-v1-training-results.ipynb'
2017-12-06 23:26:38,110;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/a17ecc8c7c4ed4424da6c3f42b61b912/raw/e6ef7691438a05d996e3e5c791a26667ea844d23/brlog.trunk-test.20171207-141943'
2017-12-06 23:26:39,158;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/MadRabbit/3a74c62b23ec1a9e42cab90a22435dc6/raw/35ea157b017c6885060685343f2ce270af8e9635/custom.jsx'
2017-12-06 23:26:40,203;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/maxlipsky/bc95db6217a8d2285eee39d2359ff9e6/raw/74eb3cace4efde770de311bf690a653e54b59af8/gistfile1.txt'
2017-12-06 23:26:41,230;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/talkingdotnet/833d5f40caf5dc2f9b7e25c339bd5e1f/raw/e3a14d3e1bb44d23160ddcba0bf8b60be47ae479/SwaggerStartupMultipeDoc.cs'
2017-12-06 23:26:42,291;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/prabakarviji/abcb0c3cdb9be68f502c69ef4fac6779/raw/3ebeb642b2545915940bb8ee495dfc26d94f7459/LinkingDemo.js'
2017-12-06 23:26:43,352;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/wildcat5566/592bd2c23adb716b7314b58d34d7dcdc/raw/67dcd8b5b1867f993bc3cb8d6325f7025f656dea/gistfile1.txt'
2017-12-06 23:26:44,268;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/lankypete/0716931145137e0ab3e2caa4946f12af/raw/5b8ba55875f913c500734c8ce744ba24bdb9d65f/counter.js'
2017-12-06 23:26:45,121;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/superxu666/faac9f9f39e9f5e871597710e0773e24/raw/d61838a3df005d9c6f5aa09f06dd470f0c7ea2f3/gistfile1.txt'
2017-12-06 23:26:46,243;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ishideo/786d3732ceca4c92f84e2ad9fae11ce0/raw/6df142100125abdbeefedc923c048732484a8ee6/max_value_importer.rb'
2017-12-06 23:26:47,337;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/JeffCohen/60e8d8e3be66d4f167b1249fb1bd451a/raw/fa75106b6c594826c893527f1572ffbca4195bab/macsetup.sh'
2017-12-06 23:26:48,347;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/evanderkoogh/f9012bc0163b6d9f2bde49046d8cf720/raw/4da5cb1ee801732b3da634e89d4d6501815b8610/gistfile1.txt'
2017-12-06 23:26:49,267;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/mrcnc/90cd76758eb11742bdd51f080a144c3c/raw/3975edcb2d18637fa665d15ccb545126d09d558f/parcels.geojson'
2017-12-06 23:26:50,847;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/eggman/e5fe0a832872c2b1cebe473c7cf6fb07/raw/fd664b8f5e74fe9cb0891a044387e62fa5b66cec/gdax-realtime.py'
2017-12-06 23:26:52,084;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/eea5625b2d22fa7495300f7e820995f7/raw/3d5102c686edaa0adf12d87daf3521c2e0a5835f/brlog.trunk-test.20171207-141114'
2017-12-06 23:26:53,458;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/jhyland87/95842f451f0c773c6a2bbb83ee677b12/raw/a3c9077664bd5182eaf969d9ae736b42a0cc8a35/script.js'
2017-12-06 23:26:54,543;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/oblitum/28834980eb0b18e51d1b553842c8eaed/raw/533a9bff61e8e6aa8b2cedddd55fd1fea6a6a044/userChrome.css'
2017-12-06 23:26:55,868;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/samuraisam/6af2cbd886b2e76cac9b8bc346718353/raw/9d43a85fdd882406bba9dc1c0c202007e7e45276/gistfile1.txt'
2017-12-06 23:26:56,869;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/yambal/e3225e09e4ee682649d2e025f4326d21/raw/aacf3f072ab45fed5021ea3c0b413899e91b6214/QuickRelux_long.ssml'
2017-12-06 23:26:58,720;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:26:58,865;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:26:58,865;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:26:58,866;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:26:58,866;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:18
duplicate of #256

**Closed** 2017-12-07 13:18 UTC
Labels: duplicate
