### ISSUE TITLE
Unhandled exception (JOpFMGK)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#250] opened 2017-12-07 00:04 UTC
Zeus version:
`1.4.2.4e0945`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 229, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 265, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.hackbusters.net', port=80): Max retries exceeded with url: /sea%2520%253cbr%2520/%253e/?amp;;sa%0A&Connection=close&X-Forwarded-For=134.38.15.132%2C+75.97.131.162%2C+73.235.143.56&User-Agent=Mozilla%2F5.0+%28X11%3B+U%3B+Linux+i686%3B+en-US%3B+rv%3A1.9.2.3%29+Gecko%2F20100401+Firefox%2F3.6.3+GTB7.1 (Caused by NewConnectionError('<urllib3.connection.HTTP...
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Welcome to the Cyclades" --verbose --batch -w --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 18:04:35,831;zeus-log;DEBUG;loading script '3com'...
2017-12-06 18:04:35,832;zeus-log;DEBUG;loading script 'googleapi'...
2017-12-06 18:04:35,833;zeus-log;DEBUG;loading script '1024'...
2017-12-06 18:04:35,833;zeus-log;DEBUG;loading script 'accellion'...
2017-12-06 18:04:35,834;zeus-log;DEBUG;loading script 'rssfeed'...
2017-12-06 18:04:35,834;zeus-log;DEBUG;loading script '4images'...
2017-12-06 18:04:35,835;zeus-log;DEBUG;loading script 'openxchange'...
2017-12-06 18:04:35,836;zeus-log;WARNING;no known plugins identified on target...
2017-12-06 18:04:35,836;zeus-log;DEBUG;loading XML data...
2017-12-06 18:04:35,837;zeus-log;INFO;attempting to get request headers for 'http://akd.apnstatic.com/media/html/sr/en/privacy.html'...
2017-12-06 18:04:35,837;zeus-log;INFO;found a request cookie, saving to file...
2017-12-06 18:04:35,838;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/akd.apnstatic.com(12).log'...
2017-12-06 18:04:35,838;zeus-log;DEBUG;fetched {'Content-Length': '192', 'Content-Encoding': 'gzip', 'Set-Cookie': 'lb_selected_pool=poolA0;expires=Fri, 08-Dec-2017 00:04:33 GMT;path=/;', 'Vary': 'Accept-Encoding', 'Server': 'Apache', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=31536000', 'Date': 'Thu, 07 Dec 2017 00:04:35 GMT', 'Content-Type': 'text/html; charset=iso-8859-1'}...
2017-12-06 18:04:35,838;zeus-log;INFO;writing found headers to log file...
2017-12-06 18:04:35,839;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/akd.apnstatic.com(12).json'...
2017-12-06 18:04:35,839;zeus-log;INFO;performing WhoIs lookup on given domain 'akd.apnstatic.com'...
2017-12-06 18:04:36,154;zeus-log;INFO;discovered raw information...
2017-12-06 18:04:36,155;zeus-log;INFO;gathering interesting information...
2017-12-06 18:04:36,157;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/whois/akd.apnstatic.com(2).json'...
2017-12-06 18:04:36,157;zeus-log;INFO;currently running on 'http://www.hackbusters.net/sea%2520%253cbr%2520/%253e/?amp;;sa' (target #6)...
2017-12-06 18:04:36,157;zeus-log;INFO;fetching target meta-data...
2017-12-06 18:04:36,158;zeus-log;INFO;random IP address generated for header '134.38.15.132'...
2017-12-06 18:04:36,158;zeus-log;INFO;random IP address generated for header '75.97.131.162'...
2017-12-06 18:04:36,158;zeus-log;INFO;random IP address generated for header '73.235.143.56'...
2017-12-06 18:04:36,382;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'HTTPConnectionPool(host='www.hackbusters.net', port=80): Max retries exceeded with url: /sea%2520%253cbr%2520/%253e/?amp;;sa%0A&Connection=close&X-Forwarded-For=134.38.15.132%2C+75.97.131.162%2C+73.235.143.56&User-Agent=Mozilla%2F5.0+%28X11%3B+U%3B+Linux+i686%3B+en-US%3B+rv%3A1.9.2.3%29+Gecko%2F20100401+Firefox%2F3.6.3+GTB7.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07cc267d10>: Failed to establish a new connection: [Errno 111] Connection refused',))'...
Traceback (most recent call last):
  File "zeus.py", line 229, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 265, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.hackbusters.net', port=80): Max retries exceeded with url: /sea%2520%253cbr%2520/%253e/?amp;;sa%0A&Connection=close&X-Forwarded-For=134.38.15.132%2C+75.97.131.162%2C+73.235.143.56&User-Agent=Mozilla%2F5.0+%28X11%3B+U%3B+Linux+i686%3B+en-US%3B+rv%3A1.9.2.3%29+Gecko%2F20100401+Firefox%2F3.6.3+GTB7.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07cc267d10>: Failed to establish a new connection: [Errno 111] Connection refused',))

2017-12-06 18:04:36,617;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-06 18:04:36,617;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-06 18:04:36,642;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-06 18:04:36,642;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-12-07 02:39
duplicate of #245

**Closed by Ekultek** 2017-12-07 02:39 UTC
Labels: duplicate
