### ISSUE TITLE
Unhandled exception (eBCzycz)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#178] opened 2017-11-28 16:07 UTC
Zeus version:
`1.3`

Firefox version:
`(52, 3)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 331, in <module>
    show_success=opt.showSuccessRate
  File "/root/Desktop/Zeus-Scanner/var/search/selenium_search.py", line 367, in parse_search_results
    req = requests.get(query_url, proxies=proxy_string, params=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.google.com.ua', port=80): Max retries exceeded with url: /search?ie=windows-1251&hl=uk&source=hp&biw=&bih=&q=inurl%3A%2Fcms%2F&gbv=1&oq=inurl%3A%2Fcms%2F&gs_l=heirloom-hp.3...214.264.0.307.11.1.0.0.0.0.0.0..0.0....0...1.1.34.heirloom-hp..11.0.0.V87tZ4HWbYg&Connection=close&User-Agent=Zeus-Scanner%2F1.3+%28Language%3DPython%2F2.7.13%3B+Platform%3DLinux%...
````

Running details:
`Linux-4.12.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py -d inurl:/cms/ -a`

Log file info:
```2017-11-28 18:07:35,795;zeus-log;INFO;log file being saved to '/root/Desktop/Zeus-Scanner/log/zeus-log-10.log'...
2017-11-28 18:07:35,795;zeus-log;INFO;using default search engine...
2017-11-28 18:07:35,795;zeus-log;INFO;starting dork scan with query 'inurl:/cms/'...
2017-11-28 18:07:35,795;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-11-28 18:07:35,795;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-11-28 18:07:35,795;zeus-log;INFO;attempting to gather query URL...
2017-11-28 18:07:35,795;zeus-log;INFO;setting up virtual display to hide the browser...
2017-11-28 18:07:35,915;zeus-log;INFO;setting the browser...
2017-11-28 18:07:40,735;zeus-log;INFO;browser will open shortly...
2017-11-28 18:07:41,669;zeus-log;INFO;searching search engine using query 'http://google.com'...
2017-11-28 18:07:44,841;zeus-log;INFO;closing the browser and continuing process..
2017-11-28 18:07:44,867;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-11-28 18:07:44,867;zeus-log;INFO;no proxy configuration detected...
2017-11-28 18:07:44,891;zeus-log;ERROR;[7;31;31mran into exception 'HTTPConnectionPool(host='www.google.com.ua', port=80): Max retries exceeded with url: /search?ie=windows-1251&hl=uk&source=hp&biw=&bih=&q=inurl%3A%2Fcms%2F&gbv=1&oq=inurl%3A%2Fcms%2F&gs_l=heirloom-hp.3...214.264.0.307.11.1.0.0.0.0.0.0..0.0....0...1.1.34.heirloom-hp..11.0.0.V87tZ4HWbYg&Connection=close&User-Agent=Zeus-Scanner%2F1.3+%28Language%3DPython%2F2.7.13%3B+Platform%3DLinux%29 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f523c857310>: Failed to establish a new connection: [Errno 101] Network is unreachable',))'...
Traceback (most recent call last):
  File "zeus.py", line 331, in <module>
    show_success=opt.showSuccessRate
  File "/root/Desktop/Zeus-Scanner/var/search/selenium_search.py", line 367, in parse_search_results
    req = requests.get(query_url, proxies=proxy_string, params=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.google.com.ua', port=80): Max retries exceeded with url: /search?ie=windows-1251&hl=uk&source=hp&biw=&bih=&q=inurl%3A%2Fcms%2F&gbv=1&oq=inurl%3A%2Fcms%2F&gs_l=heirloom-hp.3...214.264.0.307.11.1.0.0.0.0.0.0..0.0....0...1.1.34.heirloom-hp..11.0.0.V87tZ4HWbYg&Connection=close&User-Agent=Zeus-Scanner%2F1.3+%28Language%3DPython%2F2.7.13%3B+Platform%3DLinux%29 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f523c857310>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

2017-11-28 18:07:48,249;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-28 18:07:48,250;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-28 18:07:48,250;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-28 18:07:48,251;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-11-28 16:16
duplicate of #177

**Closed by Ekultek** 2017-11-28 16:16 UTC
Labels: duplicate
