### ISSUE TITLE
Google ban URL's

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#56] opened 2017-10-09 21:44 UTC
Zeus version:
`1.0.33.1770`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/var/google_search/search.py", line 161, in get_urls
    retval = bypass_ip_block(retval)
  File "/home/baal/bin/python/zeus-scanner/var/google_search/search.py", line 64, in bypass_ip_block
    splice_to_use = content_list_start[-1][-1]
IndexError: list index out of range
````

Running details:
`Linux-4.10.0-35-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:php?*index*= --verbose -s`

Log file info:
```2017-10-09 16:43:15,804;zeus-log;DEBUG;checking if the application has been run before...
2017-10-09 16:43:15,804;zeus-log;DEBUG;verifying operating system...
2017-10-09 16:43:15,825;zeus-log;DEBUG;already ran, skipping...
2017-10-09 16:43:17,771;zeus-log;DEBUG;running with options '{'runInVerbose': True, 'runSqliScan': True, 'dorkToUse': 'inurl:php?*index*='}'...
2017-10-09 16:43:17,773;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-84.log'...
2017-10-09 16:43:17,774;zeus-log;DEBUG;using default search engine (Google)...
2017-10-09 16:43:17,774;zeus-log;INFO;using default search engine...
2017-10-09 16:43:17,774;zeus-log;INFO;starting dork scan with query 'inurl:php?*index*='...
2017-10-09 16:43:17,774;zeus-log;DEBUG;checking for user-agent and proxy configuration...
2017-10-09 16:43:17,774;zeus-log;INFO;attempting to gather query URL...
2017-10-09 16:43:17,775;zeus-log;DEBUG;setting up the virtual display to hide the browser...
2017-10-09 16:43:18,009;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-09 16:43:18,009;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-09 16:43:18,009;zeus-log;DEBUG;running selenium-webdriver and launching browser...
2017-10-09 16:43:18,010;zeus-log;DEBUG;adjusting selenium-webdriver user-agent to 'Zeus-Scanner(v1.0.33.1770)::Python->v2.7'...
2017-10-09 16:43:28,794;zeus-log;INFO;browser will open shortly...
2017-10-09 16:43:31,967;zeus-log;DEBUG;searching search engine for the 'q' element (search button)...
2017-10-09 16:43:32,088;zeus-log;INFO;searching 'http://google.com' using query 'inurl:php?*index*='...
2017-10-09 16:43:36,195;zeus-log;DEBUG;obtaining URL from selenium...
2017-10-09 16:43:36,201;zeus-log;WARNING;it appears that Google is attempting to block your IP address, attempting bypass...
2017-10-09 16:43:36,412;zeus-log;ERROR;[7;31;31mzeus was unable to extract the correct URL from the ban URL 'http://ipv6.google.com/sorry/index?continue=http://www.google.com/search?ie=ISO-8859-1&hl=en&source=hp&biw=&bih=&q=inurl%3Aphp%3F*index*%3D&gbv=1&oq=inurl%3Aphp%3F*index*%3D&gs_l=heirloom-hp.3..0i131l3j0l2j0i131j0j0i131l2j0.899.1431.0.1609.18.2.0.0.0.0.98.98.1.1.0....0...1.1.34.heirloom-hp..17.1.97.fsJgHog94G4&hl=en&q=EhAmAIgDuACGgPCMXXGWS8MsGIXb784FIhkA8aeDS11kWUxSD1ojYj720fGhHcXKsbLIMgFy'...
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/var/google_search/search.py", line 161, in get_urls
    retval = bypass_ip_block(retval)
  File "/home/baal/bin/python/zeus-scanner/var/google_search/search.py", line 64, in bypass_ip_block
    splice_to_use = content_list_start[-1][-1]
IndexError: list index out of range

2017-10-09 16:44:50,172;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-09 16:44:50,172;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-09 16:44:50,180;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment] 2017-10-09 21:46
Need more URL's to be able to fix this issue

**Comment by Ekultek** [comment] 2017-10-09 21:47
```
http://ipv6.google.com/sorry/index?continue=http://www.google.com/search?ie=ISO-8859-1&hl=en&source=hp&biw=&bih=&q=inurl%3Aphp%3F*id*%3D&gbv=1&oq=inurl%3Aphp%3F*id*%3D&gs_l=heirloom-hp.3...722.1013.0.1085.15.2.0.0.0.0.0.0..0.0....0...1.1.34.heirloom-hp..15.0.0.4Ra6c8GGvFU&hl=en&q=EhAmAIgDuACGgPCMXXGWS8MsGO7c784FIhkA8aeDS3UvW6UHp5Iu3V0WlTtagFnk8_rMMgFy
```

**Comment by Ekultek** [comment] 2017-10-09 21:49
Note to self for an idea, craft a personal URL instead of trying to extract, might be easier.

**Comment by Ekultek** [comment] 2017-10-09 21:51
```
http://ipv6.google.com/sorry/index?continue=http://www.google.com/search?ie=ISO-8859-1&hl=en&source=hp&biw=&bih=&q=inurl%3Aphp%3F*index*%3D&gbv=1&oq=inurl%3Aphp%3F*index*%3D&gs_l=heirloom-hp.3..0i131l3j0l2j0i131j0j0i131l2j0.899.1431.0.1609.18.2.0.0.0.0.98.98.1.1.0....0...1.1.34.heirloom-hp..17.1.97.fsJgHog94G4&hl=en&q=EhAmAIgDuACGgPCMXXGWS8MsGIXb784FIhkA8aeDS11kWUxSD1ojYj720fGhHcXKsbLIMgFy
```

URL: `http://www.google.com/search?ie=ISO-8859-1&hl=en&source=hp&biw=&bih=&q=inurl:php?*index*=&gbv=1&oq=inurl:php?*index*=`

**Comment by Ekultek** [comment] 2017-10-10 01:22
Duplicate of #13

**Closed by Ekultek** 2017-10-10 01:22 UTC
Labels: duplicate
