### ISSUE TITLE
Unhandled exception (nBouMGb)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#259] opened 2017-12-07 05:25 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle: "index of/root" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:25:23,011;zeus-log;INFO;found match with given specifics ('msn*'), saving Gist to file
2017-12-06 23:25:23,014;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/msn(14).log'
2017-12-06 23:25:23,648;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/kjunichi/55cbcd0d34d23c2e65039e690cbd5dae/raw/b14084cebe6c1d69718c1a176634423a99750a0d/20171207.md'
2017-12-06 23:25:24,764;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/yukw777/0948e90d3d9ae0b8c7ad212794028aba/raw/05d7dfa61a3e3555d8677f77d4be828730f08579/game-v1-training-results.ipynb'
2017-12-06 23:25:26,651;zeus-log;INFO;found match with given specifics ('(http(s)?)?(.//)?(www.)?msn'), saving Gist to file
2017-12-06 23:25:26,658;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/msn(15).log'
2017-12-06 23:25:26,659;zeus-log;INFO;found match with given specifics ('(.)?msn(.)?'), saving Gist to file
2017-12-06 23:25:26,667;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/msn(16).log'
2017-12-06 23:25:26,669;zeus-log;INFO;found match with given specifics ('\bmsn'), saving Gist to file
2017-12-06 23:25:26,677;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/msn(17).log'
2017-12-06 23:25:26,733;zeus-log;INFO;found match with given specifics ('msn*'), saving Gist to file
2017-12-06 23:25:26,740;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/msn(18).log'
2017-12-06 23:25:26,740;zeus-log;INFO;found match with given specifics ('msn'), saving Gist to file
2017-12-06 23:25:26,748;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/msn(19).log'
2017-12-06 23:25:27,469;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/a17ecc8c7c4ed4424da6c3f42b61b912/raw/e6ef7691438a05d996e3e5c791a26667ea844d23/brlog.trunk-test.20171207-141943'
2017-12-06 23:25:27,947;zeus-log;INFO;found match with given specifics ('msn*'), saving Gist to file
2017-12-06 23:25:27,952;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/msn(20).log'
2017-12-06 23:25:28,748;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/MadRabbit/3a74c62b23ec1a9e42cab90a22435dc6/raw/35ea157b017c6885060685343f2ce270af8e9635/custom.jsx'
2017-12-06 23:25:29,162;zeus-log;INFO;found match with given specifics ('msn*'), saving Gist to file
2017-12-06 23:25:29,166;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/msn(21).log'
2017-12-06 23:25:29,769;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/oblitum/28834980eb0b18e51d1b553842c8eaed/raw/533a9bff61e8e6aa8b2cedddd55fd1fea6a6a044/userChrome.css'
2017-12-06 23:25:30,820;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/wynot/0889755e08ab42e2394f205aaa47c58e/raw/c3d39585aec8cc8caf7a990e49cacb3f5235b1e9/gistfile1.txt'
2017-12-06 23:25:31,907;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/wildcat5566/592bd2c23adb716b7314b58d34d7dcdc/raw/67dcd8b5b1867f993bc3cb8d6325f7025f656dea/gistfile1.txt'
2017-12-06 23:25:33,074;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/lankypete/0716931145137e0ab3e2caa4946f12af/raw/5b8ba55875f913c500734c8ce744ba24bdb9d65f/counter.js'
2017-12-06 23:25:34,092;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/superxu666/faac9f9f39e9f5e871597710e0773e24/raw/d61838a3df005d9c6f5aa09f06dd470f0c7ea2f3/gistfile1.txt'
2017-12-06 23:25:35,233;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ishideo/786d3732ceca4c92f84e2ad9fae11ce0/raw/6df142100125abdbeefedc923c048732484a8ee6/max_value_importer.rb'
2017-12-06 23:25:35,622;zeus-log;INFO;found match with given specifics ('msn*'), saving Gist to file
2017-12-06 23:25:35,627;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/msn(22).log'
2017-12-06 23:25:36,373;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/JeffCohen/60e8d8e3be66d4f167b1249fb1bd451a/raw/fa75106b6c594826c893527f1572ffbca4195bab/macsetup.sh'
2017-12-06 23:25:36,802;zeus-log;INFO;found match with given specifics ('msn*'), saving Gist to file
2017-12-06 23:25:36,808;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/msn(23).log'
2017-12-06 23:25:37,516;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/evanderkoogh/f9012bc0163b6d9f2bde49046d8cf720/raw/4da5cb1ee801732b3da634e89d4d6501815b8610/gistfile1.txt'
2017-12-06 23:25:39,350;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/eggman/e5fe0a832872c2b1cebe473c7cf6fb07/raw/fd664b8f5e74fe9cb0891a044387e62fa5b66cec/gdax-realtime.py'
2017-12-06 23:25:40,798;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/eea5625b2d22fa7495300f7e820995f7/raw/3d5102c686edaa0adf12d87daf3521c2e0a5835f/brlog.trunk-test.20171207-141114'
2017-12-06 23:25:41,517;zeus-log;INFO;found match with given specifics ('msn*'), saving Gist to file
2017-12-06 23:25:41,520;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/msn(24).log'
2017-12-06 23:25:42,521;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/jhyland87/95842f451f0c773c6a2bbb83ee677b12/raw/a3c9077664bd5182eaf969d9ae736b42a0cc8a35/script.js'
2017-12-06 23:25:43,573;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/maxlipsky/bc95db6217a8d2285eee39d2359ff9e6/raw/74eb3cace4efde770de311bf690a653e54b59af8/gistfile1.txt'
2017-12-06 23:25:44,630;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/samuraisam/6af2cbd886b2e76cac9b8bc346718353/raw/9d43a85fdd882406bba9dc1c0c202007e7e45276/gistfile1.txt'
2017-12-06 23:25:45,668;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/yambal/e3225e09e4ee682649d2e025f4326d21/raw/aacf3f072ab45fed5021ea3c0b413899e91b6214/QuickRelux_long.ssml'
2017-12-06 23:25:47,527;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:25:47,786;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:25:47,787;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:25:47,787;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:25:47,788;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:17
duplicate of #256

**Closed** 2017-12-07 13:18 UTC
Labels: duplicate
