### ISSUE TITLE
Program install error! 

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#104] opened 2017-10-16 16:25 UTC
Zeus version:
`1.0.49.ced6`

Firefox version:
`((56, 0))`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/usr/share/zeus-scanner/var/google_search/search.py", line 242, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/usr/share/zeus-scanner/var/google_search/search.py", line 88, in get_urls
    ff_display = Display(visible=0, size=(800, 600))
  File "/usr/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/usr/lib/python2.7/site-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/lib/python2.7/site-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error! 
````

Running details:
`Linux-4.13.6-1-hardened-x86_64-with-glibc2.2.5`

Commands used:
`zeus.py -d filetype:pdf -s -p`

Log file info:
```2017-10-16 11:23:26,887;zeus-log;INFO;seems this is your first time running the appication, doing setup please wait...
2017-10-16 11:24:06,870;zeus-log;INFO;installing Xvfb, required by pyvirutaldisplay...
2017-10-16 11:24:06,931;zeus-log;INFO;attempting to get firefox browser version...
2017-10-16 11:24:08,258;zeus-log;INFO;done, continuing process...
2017-10-16 11:24:08,259;zeus-log;INFO;log file being saved to '/usr/share/zeus-scanner/log/zeus-log-4.log'...
2017-10-16 11:24:08,259;zeus-log;INFO;using default search engine...
2017-10-16 11:24:08,259;zeus-log;INFO;starting dork scan with query 'filetype:pdf'...
2017-10-16 11:24:08,259;zeus-log;INFO;attempting to gather query URL...
2017-10-16 11:24:08,293;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error!' exception has been logged to current log file...
Traceback (most recent call last):
  File "/usr/share/zeus-scanner/var/google_search/search.py", line 242, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/usr/share/zeus-scanner/var/google_search/search.py", line 88, in get_urls
    ff_display = Display(visible=0, size=(800, 600))
  File "/usr/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/usr/lib/python2.7/site-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/lib/python2.7/site-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error! 

2017-10-16 11:24:56,560;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-16 11:24:56,561;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-16 11:24:56,562;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-16 11:24:56,562;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-10-16 16:30
Duplicate of #57 

- sudo rm -rf /usr/bin/geckodriver
 - cd ..
 - rm -rf zeus-scanner
 - git clone https://github.com/ekultek/zeus-scanner
 - cd zeus-scanner
 - sudo zeus.py
That will install all the dependencies needed, if for any reason that does not work, post the output of the command so I can see what's going on.

**Closed by Ekultek** 2017-10-16 16:30 UTC
Labels: duplicate, support
