### ISSUE TITLE
WebDriverException: Message: Expected [object Undefined] undefined to be a string

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#99] opened 2017-10-14 19:17 UTC
Zeus version:
`1.0.47.8f84`

Firefox version:
`Version: (55.0)`

Error info:
```Traceback (most recent call last):
  File "/opt/Zeus-Scanner/var/google_search/search.py", line 242, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/opt/Zeus-Scanner/var/google_search/search.py", line 141, in get_urls
    search.send_keys(query)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 350, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Expected [object Undefined] undefined to be a string
````

Running details:
`Linux-2.6.32-042stab120.16-x86_64-with-Ubuntu-16.04-xenial`

Commands used:
`zeus.py -d inurl:php?id=`

Log file info:
```2017-10-14 15:17:47,759;zeus-log;INFO;log file being saved to '/opt/Zeus-Scanner/log/zeus-log-6.log'...
2017-10-14 15:17:47,759;zeus-log;INFO;using default search engine...
2017-10-14 15:17:47,759;zeus-log;INFO;starting dork scan with query 'inurl:php?id='...
2017-10-14 15:17:47,759;zeus-log;INFO;attempting to gather query URL...
2017-10-14 15:17:47,876;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-14 15:17:47,876;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-14 15:17:51,182;zeus-log;INFO;browser will open shortly...
2017-10-14 15:17:51,686;zeus-log;INFO;searching 'http://google.com' using query 'inurl:php?id='...
2017-10-14 15:17:51,693;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Message: Expected [object Undefined] undefined to be a string' exception has been logged to current log file...
Traceback (most recent call last):
  File "/opt/Zeus-Scanner/var/google_search/search.py", line 242, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/opt/Zeus-Scanner/var/google_search/search.py", line 141, in get_urls
    search.send_keys(query)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 350, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Expected [object Undefined] undefined to be a string


2017-10-14 15:17:55,057;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-14 15:17:55,058;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-14 15:17:55,058;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-14 15:17:55,059;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-10-14 19:23
similar case to #85 (closed as unreproducible)

**Comment by Ekultek** [comment] 2017-10-14 19:25
So as I've been researching this I've discovered that this is a firefox bug. How it happens? No idea, Why it happens? Also no idea. But I do want to keep this one open for awhile, let me try to reproduce it..

**Comment by Ekultek** [comment] 2017-10-14 19:59
So I made a couple changes, what I'm thinking is that it has something to do with your geckodriver version, so I'm hoping this will help with it. Idk why this is happening to certain Ubuntu versions (specifically seems like 16.04) and I hate to do this, but would you please reinstall the newest version and try to run it and see what you get? I'm going to leave this open until I can figure out a actual fix for this issue. Thanks for using Zeus and for your patience, I am sorry

**Comment by Ekultek** [comment] 2017-10-15 14:26
Gonna go ahead and close this since I haven't heard anything in awhile.

**Closed by Ekultek** 2017-10-15 14:26 UTC
Labels: browser issue, bug, priority: medium
