### ISSUE TITLE
Unhandled exception (GjRaUAJ)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#249] opened 2017-12-06 23:34 UTC
Zeus version:
`1.4.2.4e0945`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 150, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
2017-12-06 17:34:33,922;zeus-log;INFO;currently running on 'http://www.kedn-china.com/cp.php?cl%3Dcp%26topid%3D0225%26pid%3D0%26catid%3D225%26nowmenuid%3D2537%26cpath%3D0225:%2Binurl:cp.php?cl%3Dcp' (target #2)...
2017-12-06 17:34:33,922;zeus-log;INFO;fetching target meta-data...
2017-12-06 17:34:33,922;zeus-log;INFO;random IP address generated for header '57.161.19.219'...
2017-12-06 17:34:33,922;zeus-log;INFO;random IP address generated for header '98.211.10.224'...
2017-12-06 17:34:33,922;zeus-log;INFO;random IP address generated for header '45.28.213.62'...
2017-12-06 17:34:34,057;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '('Connection aborted.', error(104, 'Connection reset by peer'))'...
Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 265, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:cp.php?cl=cp nowmenuid= --verbose --batch -g --x-forward --random-agent -W -E --identify-waf --identify-plugins`

Log file info:
```2017-12-06 17:34:17,535;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/karibullard/fc41c1bb79911d94de1a3eb267de88c0/raw/58aee134782c47d0648105d5d9284fd369bd2470/gistfile1.txt'...
2017-12-06 17:34:18,802;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/pbamotra/cab0f02519e0f6a86c26c685d40964cb/raw/21f13546a96ba0fa8871b13b6e96bfe41e5e5b2d/scrape_npr.py'...
2017-12-06 17:34:19,849;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/tripflex/04f4fa05726ce9f5aa5d20518c67cd82/raw/ffcdc15d0ed76b90cfd754c7c87a9efebc1c8f19/functions.php'...
2017-12-06 17:34:21,052;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/dletk/761a299e5a222e7b847f5c2a85e5fbc4/raw/fce112c3303f05ad6140d4e2b0b3e450fb5a83e8/gistfile1.txt'...
2017-12-06 17:34:22,242;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/mortn/46648b3d35dda788bab2c6d2224b7fba/raw/ec505a54bba11311295aea7a7a5073ce6dd82873/dyn-dns-gugl.sh'...
2017-12-06 17:34:23,241;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/hasannkursunn/3f67dd7929690917b8cfc9c87b9fb262/raw/e5bf3c45ae147d17215f6cd57d4d46bef2051b94/gistfile1.txt'...
2017-12-06 17:34:24,546;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/fd9f93e12117d5c7ce4b2d3a60ba032d/raw/27d3f048faf29c2b7c08ca8a5c765f2d7f20eeac/brlog.trunk-test.20171207-082425'...
2017-12-06 17:34:25,820;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/elmasse/1fcc35dea402c6df5040f010cf6f3678/raw/e418c156d5f5292fb83f9fd8e17b11efd64ca809/Date.toLocaleString'...
2017-12-06 17:34:26,910;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rexs123/52e2fdb75a2a0c7f3a855c7173b4392b/raw/7d717e524cdcdfbf9cd210d4293644320acf6201/DiscordWebhook.php'...
2017-12-06 17:34:28,189;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/dimohamdy/f59d4ba089a5e2ae491be924fc138638/raw/5e94dbb48add6a7abdf84e56d0dda2955cf6363d/iconVersioning.sh'...
2017-12-06 17:34:29,405;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/StephanieReilly/86927bd63b411e1bcc01888ce12ce649/raw/5ab764c276241047a97b7def5f717958d45960b4/.block'...
2017-12-06 17:34:30,636;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/BrandenSchwartz/b073d6eb1add6211bb71b33961aedd0a/raw/d12da052083016307e81428acbff7b793cc60c8e/HeaderPOC.ino'...
2017-12-06 17:34:31,692;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/edwingustafson/ed4bcb3800e5116ae364e496ad418825/raw/139d50c03d943236acdf1d95c9d1cba8ddeeb05f/.bash_prompt'...
2017-12-06 17:34:32,840;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/nbadmin-ibm/245b2e506016c2f9c1482e6945824ef3/raw/efbc0604d6a7b36c474d02d01d92656edbb00360/AX_LONYPPROD_NB_GIST_LIST1.ipynb'...
2017-12-06 17:34:33,907;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'...
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 150, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
2017-12-06 17:34:33,922;zeus-log;INFO;currently running on 'http://www.kedn-china.com/cp.php?cl%3Dcp%26topid%3D0225%26pid%3D0%26catid%3D225%26nowmenuid%3D2537%26cpath%3D0225:%2Binurl:cp.php?cl%3Dcp' (target #2)...
2017-12-06 17:34:33,922;zeus-log;INFO;fetching target meta-data...
2017-12-06 17:34:33,922;zeus-log;INFO;random IP address generated for header '57.161.19.219'...
2017-12-06 17:34:33,922;zeus-log;INFO;random IP address generated for header '98.211.10.224'...
2017-12-06 17:34:33,922;zeus-log;INFO;random IP address generated for header '45.28.213.62'...
2017-12-06 17:34:34,057;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '('Connection aborted.', error(104, 'Connection reset by peer'))'...
Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 265, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2017-12-06 17:34:34,359;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-06 17:34:34,359;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-06 17:34:34,385;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-06 17:34:34,386;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-12-07 02:39
duplicate of #245

**Closed by Ekultek** 2017-12-07 02:39 UTC
Labels: duplicate
