### ISSUE TITLE
Unhandled exception (nrdBykf)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#274] opened 2017-12-07 05:39 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Network Camera NetworkCamera" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:39:04,742;zeus-log;DEBUG;loading script 'bmcremedy'
2017-12-06 23:39:04,743;zeus-log;DEBUG;loading script 'abyss'
2017-12-06 23:39:04,743;zeus-log;DEBUG;loading script '68classified'
2017-12-06 23:39:04,749;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:39:04,756;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:39:04,760;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:39:04,761;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:39:04,767;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:39:04,768;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:39:04,823;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:39:04,832;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:39:04,839;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:39:04,889;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:39:04,889;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:39:04,894;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:39:04,900;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:39:04,906;zeus-log;INFO;possible plugin identified as 'JQuery'
2017-12-06 23:39:04,906;zeus-log;INFO;possible plugin identified as 'Open-Graph-Protocol'
2017-12-06 23:39:04,906;zeus-log;INFO;possible plugin identified as 'HTML5'
2017-12-06 23:39:04,906;zeus-log;DEBUG;loading XML data
2017-12-06 23:39:04,907;zeus-log;INFO;attempting to get request headers for 'http://www.bbc.co.uk/news/uk-england-humber-42252723'
2017-12-06 23:39:04,908;zeus-log;INFO;found a request cookie, saving to file
2017-12-06 23:39:04,908;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.bbc.co.uk-cookie.log'
2017-12-06 23:39:04,909;zeus-log;DEBUG;fetched {'Vary': 'X-CDN,X-BBC-Edge-Cache,Accept-Encoding', 'X-LB-NoCache': 'true', 'Content-Length': '29545', 'X-Cache-Action': 'MISS', 'Content-Language': 'en-GB', 'Content-Encoding': 'gzip', 'X-PAL-Host': 'pal187.back.live.telhc.local:80', 'Cache-Control': 'private, max-age=60, stale-while-revalidate', 'X-Cache-Age': '0', 'Server': 'Apache', 'Connection': 'keep-alive', 'X-News-Cache-Id': '96301', 'Set-Cookie': 'BBC-UID=15fa62782d83df1646e707fba181479bc5c0b212ee4803d9e3f54b2c586ade700python-requests/2.18.4; expires=Mon, 06-Dec-21 05:39:03 GMT; path=/; domain=.bbc.co.uk', 'Date': 'Thu, 07 Dec 2017 05:39:03 GMT', 'X-News-Data-Centre': 'telhc', 'Content-Type': 'text/html; charset=utf-8'}
2017-12-06 23:39:04,909;zeus-log;INFO;writing found headers to log file
2017-12-06 23:39:04,910;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.bbc.co.uk(2).json'
2017-12-06 23:39:04,910;zeus-log;INFO;searching a total of 5 pages of Gists for 'www.bbc.co.uk'
2017-12-06 23:39:04,910;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:39:05,444;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:39:05,958;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:39:06,468;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:39:07,055;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:39:07,567;zeus-log;DEBUG;found a total of 53 links to search
2017-12-06 23:39:08,141;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rajegannathan/222d72698580c2e9b2bdbf2cc887c12d/raw/badbb7146de1bb73a72af49a14f6bbec9bbd9d65/racist-ai.ipynb'
2017-12-06 23:39:09,264;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/debashisbarman/f2a708ff8fb8e9a68463ea014e73b062/raw/4a1b37990daaae58d49aa454ec79497141eee61c/init.coffee'
2017-12-06 23:39:10,442;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/d14a2f9a72c2d721745992b56bc53d11/raw/6569bf2cfbe63f7dd7de177f1bc042754288e52b/brlog.trunk-test.20171207-142233'
2017-12-06 23:39:11,803;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/499940e908907614cff8f076937be6c2/raw/42294004b447d32f843d6ebd11f5d89dc6a95489/brlog.trunk-test.20171207-143132'
2017-12-06 23:39:12,243;zeus-log;INFO;found match with given specifics ('bbc*'), saving Gist to file
2017-12-06 23:39:12,248;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/bbc(3).log'
2017-12-06 23:39:13,027;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/eb5258165c582ded1c8328438e4b7f6b/raw/059a54383f2781763f91892b690ac8bb0f08eb1a/brlog.trunk-test.20171207-143100'
2017-12-06 23:39:14,512;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:39:14,652;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:39:14,653;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:39:14,653;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:39:14,654;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:23
duplicate of #256

**Closed** 2017-12-07 13:24 UTC
Labels: duplicate
