### ISSUE TITLE
Program install error! 

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#79] opened 2017-10-12 11:29 UTC
Zeus version:
`1.0.39`

Error info:
```Traceback (most recent call last):
  File "/root/Desktop/zues/var/google_search/search.py", line 248, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/root/Desktop/zues/var/google_search/search.py", line 82, in get_urls
    ff_display = Display(visible=0, size=(800, 600))
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error! 
````

Running details:
`Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py -l /root/Desktop/steam.txt -s -p -i -M`

Log file info:
```2017-10-12 07:29:27,334;zeus-log;INFO;log file being saved to '/root/Desktop/zues/log/zeus-log-7.log'...
2017-10-12 07:29:27,334;zeus-log;INFO;using default search engine...
2017-10-12 07:29:27,335;zeus-log;INFO;starting dork scan with query 'cat.asp?cat=Steam'...
2017-10-12 07:29:27,336;zeus-log;INFO;attempting to gather query URL...
2017-10-12 07:29:27,343;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error!' exception has been logged to current log file...
Traceback (most recent call last):
  File "/root/Desktop/zues/var/google_search/search.py", line 248, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/root/Desktop/zues/var/google_search/search.py", line 82, in get_urls
    ff_display = Display(visible=0, size=(800, 600))
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error! 

2017-10-12 07:29:30,814;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-12 07:29:30,814;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-12 07:29:30,815;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment] 2017-10-12 13:51
Duplicate of #57 

A couple of things that are wrong with these arguments that you passed (`zeus.py -l /root/Desktop/steam.txt -s -p -i -M`)

 - Multiple pages only works with singular dorks for now
 - You cannot run multiple attacks at the same time yet (not implemented yet) if you want to run multiple attacks at the same time, thats what the file enumeration flag is for (`-f <PATH-TO-FILE>`)
 - You did not specify how many links to find with the `-L` flag
 - You did not run `pip install -r -requirements.txt` or `sudo python zeus.py`

If for any reason this happens again, you need to install `Xvfb` using `sudo apt-get install xvfb`

**Closed by Ekultek** 2017-10-12 13:51 UTC
Labels: duplicate, support
