### ISSUE TITLE
Unhandled exception (fPJvIMX)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#251] opened 2017-12-07 00:05 UTC
Zeus version:
`1.4.2.4e0945`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/root/Escritorio/zeus-scanner/lib/header_check/__init__.py", line 263, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/root/Escritorio/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='twwom.net', port=80): Max retries exceeded with url: /?page_id=15%0A&Connection=close&User-Agent=Zeus-Scanner%2F1.4.2.4e0945+%28Language%3DPython%2F2.7.14%3B+Platform%3DLinux%29 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fde1a850650>, 'Connection to twwom.net timed out. (connect timeout=20)'))
````

Running details:
`Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py -d twwom.net -p`

Log file info:
```2017-12-07 01:04:10,241;zeus-log;INFO;log file being saved to '/root/Escritorio/zeus-scanner/log/zeus-log-10.log'...
2017-12-07 01:04:10,241;zeus-log;INFO;using default search engine...
2017-12-07 01:04:10,241;zeus-log;INFO;starting dork scan with query 'twwom.net'...
2017-12-07 01:04:10,242;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-12-07 01:04:10,242;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-12-07 01:04:10,242;zeus-log;INFO;attempting to gather query URL...
2017-12-07 01:04:10,242;zeus-log;INFO;setting up virtual display to hide the browser...
2017-12-07 01:04:10,374;zeus-log;INFO;setting the browser...
2017-12-07 01:04:16,616;zeus-log;INFO;browser will open shortly...
2017-12-07 01:04:17,511;zeus-log;INFO;searching search engine using query 'twwom.net'...
2017-12-07 01:04:20,767;zeus-log;INFO;closing the browser and continuing process..
2017-12-07 01:04:20,805;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-12-07 01:04:20,805;zeus-log;INFO;no proxy configuration detected...
2017-12-07 01:04:21,158;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.4.2.4e0945 (Language=Python/2.7.14; Platform=Linux)'...
2017-12-07 01:04:21,169;zeus-log;INFO;successfully wrote found items to '/root/Escritorio/zeus-scanner/log/url-log/url-log-4.log'...
2017-12-07 01:04:21,169;zeus-log;INFO;found a total of 18 URLs with given query 'twwom.net'...
2017-12-07 01:04:21,169;zeus-log;INFO;currently running on 'http://twwom.net/?page_id=15' (target #1)...
2017-12-07 01:04:21,169;zeus-log;INFO;fetching target meta-data...
2017-12-07 01:04:41,208;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'HTTPConnectionPool(host='twwom.net', port=80): Max retries exceeded with url: /?page_id=15%0A&Connection=close&User-Agent=Zeus-Scanner%2F1.4.2.4e0945+%28Language%3DPython%2F2.7.14%3B+Platform%3DLinux%29 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fde1a850650>, 'Connection to twwom.net timed out. (connect timeout=20)'))'...
Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/root/Escritorio/zeus-scanner/lib/header_check/__init__.py", line 263, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/root/Escritorio/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='twwom.net', port=80): Max retries exceeded with url: /?page_id=15%0A&Connection=close&User-Agent=Zeus-Scanner%2F1.4.2.4e0945+%28Language%3DPython%2F2.7.14%3B+Platform%3DLinux%29 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fde1a850650>, 'Connection to twwom.net timed out. (connect timeout=20)'))

2017-12-07 01:05:24,047;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-07 01:05:24,047;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-07 01:05:24,048;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-07 01:05:24,048;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-12-07 02:39
duplicate of #245

**Closed by Ekultek** 2017-12-07 02:39 UTC
Labels: duplicate
