### ISSUE TITLE
WebDriverException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#87] opened 2017-10-13 10:22 UTC
Zeus version:
`1.0.42.49ab`

Error info:
```Traceback (most recent call last):
  File "/root/Desktop/Zeus-Scanner/var/google_search/search.py", line 233, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/root/Desktop/Zeus-Scanner/var/google_search/search.py", line 126, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Unable to find a matching set of capabilities
````

Running details:
`Linux-4.2.0-22-generic-x86_64-with-Ubuntu-15.10-wily`

Commands used:
`zeus.py -d site:*.gov.tw inurl:?id=`

Log file info:
```2017-10-13 03:22:33,503;zeus-log;INFO;seems this is your first time running the appication, doing setup please wait...
2017-10-13 03:22:33,620;zeus-log;INFO;done, continuing process...
2017-10-13 03:22:33,620;zeus-log;INFO;log file being saved to '/root/Desktop/Zeus-Scanner/log/zeus-log-6.log'...
2017-10-13 03:22:33,620;zeus-log;INFO;using default search engine...
2017-10-13 03:22:33,620;zeus-log;INFO;starting dork scan with query 'site:*.gov.tw inurl:?id='...
2017-10-13 03:22:33,620;zeus-log;INFO;attempting to gather query URL...
2017-10-13 03:22:33,750;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-13 03:22:33,751;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-13 03:22:34,901;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Message: Unable to find a matching set of capabilities' exception has been logged to current log file...
Traceback (most recent call last):
  File "/root/Desktop/Zeus-Scanner/var/google_search/search.py", line 233, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/root/Desktop/Zeus-Scanner/var/google_search/search.py", line 126, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Unable to find a matching set of capabilities


2017-10-13 03:22:44,029;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-13 03:22:44,029;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-13 03:22:44,029;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment] 2017-10-13 13:08
Duplicate of #89

**Closed by Ekultek** 2017-10-13 13:08 UTC
Labels: duplicate
