### ISSUE TITLE
Unhandled exception (vNHKutt)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#247] opened 2017-12-06 23:28 UTC
Zeus version:
`1.4.2.4e0945`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 265, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:cp.php?cl=cp nowmenuid= --verbose --batch -w --x-forward --random-agent --tamper=uppercase,lowercase,hex,obfuscateordinal -W -E --identify-waf --identify-plugins`

Log file info:
```2017-12-06 17:28:26,858;zeus-log;DEBUG;loading script '3com'...
2017-12-06 17:28:26,859;zeus-log;DEBUG;loading script 'googleapi'...
2017-12-06 17:28:26,860;zeus-log;DEBUG;loading script '1024'...
2017-12-06 17:28:26,860;zeus-log;DEBUG;loading script 'accellion'...
2017-12-06 17:28:26,861;zeus-log;DEBUG;loading script 'rssfeed'...
2017-12-06 17:28:26,861;zeus-log;DEBUG;loading script '4images'...
2017-12-06 17:28:26,862;zeus-log;DEBUG;loading script 'openxchange'...
2017-12-06 17:28:26,863;zeus-log;INFO;possible plugin identified as 'JQuery'...
2017-12-06 17:28:26,863;zeus-log;DEBUG;loading XML data...
2017-12-06 17:28:26,864;zeus-log;INFO;attempting to get request headers for 'http://www.kedn-china.com/cp.php?cl%3Dcp%26topid%3D0225%26pid%3D0%26catid%3D225%26nowmenuid%3D2537%26cpath%3D0225:%2Binurl:cp.php?cl%3Dcp'...
2017-12-06 17:28:26,864;zeus-log;INFO;found a request cookie, saving to file...
2017-12-06 17:28:26,865;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.kedn(1).log'...
2017-12-06 17:28:26,865;zeus-log;DEBUG;fetched {'X-Powered-By': 'PHP/5.4.45', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'PHPSESSID=3t1705vtlfbbomds25pr8lsrm5; path=/, language=en; expires=Thu, 07-Dec-2017 23:29:26 GMT; path=/', 'Expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'Server': 'nginx/1.13.3', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Date': 'Wed, 06 Dec 2017 23:28:26 GMT', 'Content-Type': 'text/html; charset=UTF-8'}...
2017-12-06 17:28:26,866;zeus-log;INFO;writing found headers to log file...
2017-12-06 17:28:26,866;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.kedn(1).json'...
2017-12-06 17:28:26,866;zeus-log;INFO;performing WhoIs lookup on given domain 'www.kedn-china.com'...
2017-12-06 17:28:27,214;zeus-log;INFO;discovered raw information...
2017-12-06 17:28:27,215;zeus-log;INFO;gathering interesting information...
2017-12-06 17:28:27,217;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/whois/www.kedn(1).json'...
2017-12-06 17:28:27,217;zeus-log;INFO;currently running on 'http://www.forungloves.com/cp.php?cl%3Dcp%26nowmenuid%3D20112315%2Binurl:cp.php?cl%3Dcp' (target #3)...
2017-12-06 17:28:27,217;zeus-log;INFO;fetching target meta-data...
2017-12-06 17:28:27,218;zeus-log;INFO;random IP address generated for header '131.60.171.204'...
2017-12-06 17:28:27,218;zeus-log;INFO;random IP address generated for header '10.23.133.109'...
2017-12-06 17:28:27,218;zeus-log;INFO;random IP address generated for header '176.228.65.173'...
2017-12-06 17:28:27,887;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '('Connection aborted.', error(104, 'Connection reset by peer'))'...
Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 265, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2017-12-06 17:28:28,285;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-06 17:28:28,285;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-06 17:28:28,314;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-06 17:28:28,314;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-12-07 02:39
duplicate of #245

**Closed by Ekultek** 2017-12-07 02:39 UTC
Labels: duplicate
