### ISSUE TITLE
WebDriverException: Message: Process unexpectedly closed with status: 255 (zpkqhZL)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#160] opened 2017-11-19 15:49 UTC
Zeus version:
`1.2.22.4b7f2f`

Firefox version:
`failed to start`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/data/software/sec/zeus-scanner/var/google_search/search.py", line 415, in parse_search_results
    tor=tor, batch=batch
  File "/data/software/sec/zeus-scanner/var/google_search/search.py", line 235, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use, executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Process unexpectedly closed with status: 255
````

Running details:
`Linux-4.13.0-parrot10-amd64-x86_64-with-Parrot-3.10-intruder`

Commands used:
`zeus.py --dork=inurl:php?id= --proxy=socks5://127.0.0.1:1082 --random-agent`

Log file info:
```2017-11-19 23:47:11,057;zeus-log;INFO;log file being saved to '/data/software/sec/zeus-scanner/log/zeus-log-7.log'...
2017-11-19 23:47:11,058;zeus-log;INFO;using default search engine...
2017-11-19 23:47:11,058;zeus-log;INFO;starting dork scan with query 'inurl:php?id='...
2017-11-19 23:47:11,058;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-11-19 23:47:11,058;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-11-19 23:47:11,058;zeus-log;INFO;attempting to gather query URL...
2017-11-19 23:47:11,171;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-11-19 23:47:11,171;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-11-19 23:47:15,149;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Message: Process unexpectedly closed with status: 255' exception has been logged to current log file...
Traceback (most recent call last):
  File "/data/software/sec/zeus-scanner/var/google_search/search.py", line 415, in parse_search_results
    tor=tor, batch=batch
  File "/data/software/sec/zeus-scanner/var/google_search/search.py", line 235, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use, executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Process unexpectedly closed with status: 255


2017-11-19 23:49:13,040;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-19 23:49:13,041;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-19 23:49:13,041;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-19 23:49:13,042;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
2017-11-19 23:49:13,216;zeus-log;ERROR;[7;31;31mfailed to run firefox...[0m
```

**Comment by Ekultek** [comment] 2017-11-19 18:02
Need you to post the info from the geckodriver log file

**Comment by yangyangwithgnu** [comment] 2017-11-20 03:00
i'm sorry, i can not find geckodriver log file, anyone can tell me the path ?

**Comment by Ekultek** [comment] 2017-11-20 03:30
Should be in the zeus folder, geckodriver.log.

If you can’t find it do a full search for it.

Also try reinstalling Firefox

**Comment by yangyangwithgnu** [comment] 2017-11-20 05:18
$nl geckodriver.log
     1	1511155017163	geckodriver	INFO	geckodriver 0.19.0
     2	1511155017175	geckodriver	INFO	Listening on 127.0.0.1:58757
     3	Reading profile /etc/firejail/firefox.profile
     4	Reading profile /etc/firejail/disable-common.inc
     5	Reading profile /etc/firejail/disable-devel.inc
     6	Reading profile /etc/firejail/disable-programs.inc
     7	Reading profile /etc/firejail/whitelist-common.inc
     8	Warning: noroot option is not available
     9	***
    10	*** Warning: cannot whitelist Downloads directory
    11	*** 	Any file saved will be lost when the sandbox is closed.
    12	*** 	Please create a proper Downloads directory for your application.
    13	***
    14	1511155018583	mozrunner::runner	INFO	Running command: "/usr/local/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.KPMrqP4e9Uin"
    15	Reading profile /etc/firejail/firefox.profile
    16	Reading profile /etc/firejail/disable-common.inc
    17	Reading profile /etc/firejail/disable-devel.inc
    18	Reading profile /etc/firejail/disable-programs.inc
    19	Reading profile /etc/firejail/whitelist-common.inc
    20	Warning: noroot option is not available
    21	***
    22	*** Warning: cannot whitelist Downloads directory
    23	*** 	Any file saved will be lost when the sandbox is closed.
    24	*** 	Please create a proper Downloads directory for your application.
    25	***
    26	Blacklist violations are logged to syslog
    27	Parent pid 2133, child pid 2134
    28	The new log directory is /proc/2134/root/var/log
       
    29	Parent is shutting down, bye...
    30	1511155018918	geckodriver	INFO	geckodriver 0.19.0
    31	1511155018930	geckodriver	INFO	Listening on 127.0.0.1:41515
    32	Reading profile /etc/firejail/firefox.profile
    33	Reading profile /etc/firejail/disable-common.inc
    34	Reading profile /etc/firejail/disable-devel.inc
    35	Reading profile /etc/firejail/disable-programs.inc
    36	Reading profile /etc/firejail/whitelist-common.inc
    37	Warning: noroot option is not available
    38	***
    39	*** Warning: cannot whitelist Downloads directory
    40	*** 	Any file saved will be lost when the sandbox is closed.
    41	*** 	Please create a proper Downloads directory for your application.
    42	***
    43	1511155020205	mozrunner::runner	INFO	Running command: "/usr/local/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.JLwpm1OPX0U3"
    44	Reading profile /etc/firejail/firefox.profile
    45	Reading profile /etc/firejail/disable-common.inc
    46	Reading profile /etc/firejail/disable-devel.inc
    47	Reading profile /etc/firejail/disable-programs.inc
    48	Reading profile /etc/firejail/whitelist-common.inc
    49	Warning: noroot option is not available
    50	***
    51	*** Warning: cannot whitelist Downloads directory
    52	*** 	Any file saved will be lost when the sandbox is closed.
    53	*** 	Please create a proper Downloads directory for your application.
    54	***
    55	Blacklist violations are logged to syslog
    56	Parent pid 2165, child pid 2166
    57	The new log directory is /proc/2166/root/var/log
       
    58	Parent is shutting down, bye...

**Comment by Ekultek** [comment] 2017-11-20 15:31
I am unable to reproduce this, have you gotten it since?

**Comment by Ekultek** [comment] 2017-11-20 16:11
So as I said I am unable to reproduce this, so I'm going to add it as unreproducible, my advice to you is to reinstall Firefox and then reinstall Zeus, you can do that by doing the following:

```
for pid in $(ps -ef | grep "firefox" | awk '{print $2}'); do kill -9 ${pid}; done > /dev/null 2>&1 && mv ~/.mozilla ~/.mozilla.old && sudo apt-get update && sudo apt-get --purge --reinstall install firefox 
```

If that doesn't work completely remove Firefox and reinstall it. This seems to be an issue with your Firefox more then anything. So try that and I'll leave this open for 24 hours in case anymore issues arise that I can help you with.

**Comment by Ekultek** [comment] 2017-11-21 17:39
It's been about 24 hours, no issues seem to have persisted. Closing

**Closed by Ekultek** 2017-11-21 17:39 UTC
Labels: unreproducable
