### ISSUE TITLE
Release Firefox

### ISSUE THREAD

**Issue by fo0nikens** [Ekultek/Zeus-Scanner#157] opened 2017-11-18 13:30 UTC
# What's the problem

Firefox 57.0 (32-bit)
[14:23:30 INFO] attempting to get firefox browser version...
[14:23:30 CRITICAL] your current firefox version is not supported by Zeus...

# Running context

 - Operating system: Linux Mint 4.8.0-58-generic

 - Zeus version: v1.2.20.d60ad9(revision)

# Any idea on a solution?

# Full console commands run
only sudo ./zeus after fresh install

# Stacktrace (if applicable)

# Full file log information
2017-11-18 14:23:09,438;zeus-log;INFO;seems this is your first time running the application, doing setup please wait...
2017-11-18 14:23:18,663;zeus-log;INFO;installing Xvfb, required by pyvirutaldisplay...
2017-11-18 14:23:30,697;zeus-log;INFO;attempting to get firefox browser version...
2017-11-18 14:23:30,819;zeus-log;CRITICAL;your current firefox version is not supported by Zeus...

**Comment by Ekultek** [comment] 2017-11-18 13:38
Zeus is only compatible with certain Firefox versions. This is a duplicate of #151 if you want to upgrade Firefox then you can do so with this https://github.com/Ekultek/Zeus-Scanner/blob/master/etc/scripts/reinstall.sh

**Comment by Ekultek** [comment] 2017-11-18 13:52
after some thought, there's not reason that I should not support 57, so it is now supported with https://github.com/Ekultek/Zeus-Scanner/commit/8b57b6c1cfe6bc4c9d7688effd8fc2f645d4cada

**Closed by Ekultek** 2017-11-18 13:52 UTC

**Comment by Nigrini** [comment] 2019-02-18 12:36
Any chance that you can build in support for Firefox Quantum 60.5.0esr
