### ISSUE TITLE
ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //laravel.com:16992/index.htm (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f05b0dee2d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#59] opened 2017-10-11 11:49 UTC
Zeus version:
`1.0.36.6a42`

Error info:
```Traceback (most recent call last):
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 101, in main_intel_amt
    json_data = __get_hardware(url, agent=agent, proxy=proxy)
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 59, in __get_hardware
    req = __get_raw_data(target, 'hw-sys', agent=agent, proxy=proxy)
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 51, in __get_raw_data
    'Authorization': __get_auth_headers(target),
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 22, in __get_auth_headers
    }, proxies=proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //laravel.com:16992/index.htm (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f05b0dee2d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
````

Running details:
`Linux-4.4.0-1022-aws-x86_64-with-Ubuntu-16.04-xenial`

Commands used:
`zeus.py -r -i`

Log file info:
```2017-10-11 11:49:02,722;zeus-log;INFO;log file being saved to '/home/ubuntu/Zeus-Scanner/log/zeus-log-13.log'...
2017-10-11 11:49:02,723;zeus-log;INFO;using default search engine...
2017-10-11 11:49:02,725;zeus-log;INFO;using random dork 'pagina.php?go=' as the search query...
2017-10-11 11:49:02,725;zeus-log;INFO;attempting to gather query URL...
2017-10-11 11:49:02,868;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-11 11:49:02,868;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-11 11:49:06,811;zeus-log;INFO;browser will open shortly...
2017-10-11 11:49:07,312;zeus-log;INFO;searching 'http://google.com' using query 'pagina.php?go='...
2017-10-11 11:49:10,415;zeus-log;INFO;closing the browser and continuing process..
2017-10-11 11:49:10,442;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-11 11:49:10,444;zeus-log;INFO;no proxy configuration detected...
2017-10-11 11:49:10,735;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.36.6a42)::Python->v2.7'...
2017-10-11 11:49:10,738;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:49:10,738;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:49:10,738;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:49:10,739;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:49:10,739;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:49:10,739;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:49:10,739;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:49:10,740;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:49:10,740;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:49:10,740;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:49:10,740;zeus-log;INFO;found a total of 14 URL's with a GET parameter...
2017-10-11 11:49:10,741;zeus-log;INFO;successfully wrote found items to '/home/ubuntu/Zeus-Scanner/log/url-log/url-log-11.log'...
2017-10-11 11:49:13,303;zeus-log;INFO;attempting to connect to 'https://laravel.com' and get hardware info...
2017-10-11 11:49:13,303;zeus-log;INFO;getting raw information...
2017-10-11 11:49:13,303;zeus-log;INFO;header value not established, attempting to get bypass...
2017-10-11 11:49:13,346;zeus-log;ERROR;ran into exception 'HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //laravel.com:16992/index.htm (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f05b0dee2d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))', cannot continue...
Traceback (most recent call last):
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 101, in main_intel_amt
    json_data = __get_hardware(url, agent=agent, proxy=proxy)
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 59, in __get_hardware
    req = __get_raw_data(target, 'hw-sys', agent=agent, proxy=proxy)
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 51, in __get_raw_data
    'Authorization': __get_auth_headers(target),
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 22, in __get_auth_headers
    }, proxies=proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //laravel.com:16992/index.htm (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f05b0dee2d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

2017-10-11 11:49:35,660;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-11 11:49:35,660;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-11 11:49:35,663;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment] 2017-10-11 12:19
I can't reproduce this, where you trying to use a VPN or proxy behind zeus?

```
baal@baal-Aspire-5733Z:~/bin/python/zeus-scanner$ sudo !!
sudo python zeus.py -d "pagina.php?go=" -i
[sudo] password for baal: 
Attacking targets without consent is not only illegal, but it is unethical and frowned upon in most countries. By installing this program you are agreeing that you are responsible for your own actions, you are over the age of 18 or legally considered an adult in your place of origin, and that you will obey all laws, regulations, and rules set forth by your place of origin. You will only see this disclaimer once. If you agree to the conditions type 'yes'...yes
[07:17:18 INFO] seems this is your first time running the appication, doing setup please wait...
[07:17:19 INFO] done, continuing process...

    __          __________                             __   
   / /          \____    /____  __ __  ______          \ \  
  / /    ______   /     // __ \|  |  \/  ___/  ______   \ \ 
  \ \   /_____/  /     /\  ___/|  |  /\___ \  /_____/   / / 
   \_\          /_______ \___  >____//____  >          /_/  
                       \/   \/           \/  v1.0.36.6a42(revision)
	https://github.com/ekultek/zeus-scanner.git
		Advanced Dork Searching...


[*] starting up at 07:17:19..


[07:17:19 INFO] log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-2.log'...
[07:17:19 INFO] using default search engine...
http://google.com
[07:17:19 INFO] starting dork scan with query 'pagina.php?go='...
[07:17:19 INFO] attempting to gather query URL...
[07:17:20 INFO] firefox browser display will be hidden while it performs the query...
[07:17:20 WARNING] your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
[07:17:45 INFO] browser will open shortly...
[07:17:50 INFO] searching 'http://google.com' using query 'pagina.php?go='...
[07:17:54 INFO] closing the browser and continuing process..
[07:17:55 INFO] URL successfully gathered, searching for GET parameters...
[07:17:55 INFO] no proxy configuration detected...
[07:17:55 INFO] adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.36.6a42)::Python->v2.7'...
[07:17:55 INFO] received webcache URL, extracting URL from webcache...
[07:17:55 INFO] received webcache URL, extracting URL from webcache...
[07:17:55 INFO] received webcache URL, extracting URL from webcache...
[07:17:55 INFO] received webcache URL, extracting URL from webcache...
[07:17:55 INFO] received webcache URL, extracting URL from webcache...
[07:17:55 INFO] received webcache URL, extracting URL from webcache...
[07:17:55 INFO] received webcache URL, extracting URL from webcache...
[07:17:55 INFO] received webcache URL, extracting URL from webcache...
[07:17:55 INFO] received webcache URL, extracting URL from webcache...
[07:17:55 INFO] received webcache URL, extracting URL from webcache...
[07:17:55 INFO] found a total of 14 URL's with a GET parameter...
[07:17:55 INFO] successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-1.log'...
[07:17:55 PROMPT] would you like to process found URL: 'https://laravel.com/'[y/N]: y
[07:17:59 INFO] attempting to connect to 'https://laravel.com' and get hardware info...
[07:17:59 INFO] getting raw information...
[07:17:59 INFO] header value not established, attempting to get bypass...
[07:18:09 ERROR] failed to connect on 'https://laravel.com', skipping...
[07:18:09 PROMPT] would you like to process found URL: 'https://www.godaddy.com/help/view-or-change-your-php-version-3937'[y/N]: y
[07:18:14 INFO] attempting to connect to 'https://www.godaddy.com' and get hardware info...
[07:18:14 INFO] getting raw information...
[07:18:14 INFO] header value not established, attempting to get bypass...
[07:18:24 ERROR] failed to connect on 'https://www.godaddy.com', skipping...
[07:18:24 PROMPT] would you like to process found URL: 'https://www.owasp.org/+pagina.php?go='[y/N]: n
[07:18:55 WARNING] skipping 'https://www.owasp.org/+pagina.php?go='...
[07:18:55 PROMPT] would you like to process found URL: 'https://laravel.com/+pagina.php?go='[y/N]: n
[07:18:55 WARNING] skipping 'https://laravel.com/+pagina.php?go='...
[07:18:55 PROMPT] would you like to process found URL: 'http://php.net/manual/es/language.exceptions.php'[y/N]: n
[07:18:56 WARNING] skipping 'http://php.net/manual/es/language.exceptions.php'...
[07:18:56 PROMPT] would you like to process found URL: 'https://www.godaddy.com/help/view-or-change-your-php-version-3937+pagina.php?go='[y/N]: n
[07:18:56 WARNING] skipping 'https://www.godaddy.com/help/view-or-change-your-php-version-3937+pagina.php?go='...
[07:18:56 PROMPT] would you like to process found URL: 'https://wordpress.org/plugins/insert-php/'[y/N]: n
[07:18:57 WARNING] skipping 'https://wordpress.org/plugins/insert-php/'...
[07:18:57 PROMPT] would you like to process found URL: 'http://ccm.net/faq/9296-php-redirect-to-another-page'[y/N]: n
[07:18:57 WARNING] skipping 'http://ccm.net/faq/9296-php-redirect-to-another-page'...
[07:18:57 PROMPT] would you like to process found URL: 'https://www.w3schools.com/'[y/N]: n
[07:18:58 WARNING] skipping 'https://www.w3schools.com/'...
[07:18:58 PROMPT] would you like to process found URL: 'https://wordpress.org/plugins/insert-php/+pagina.php?go='[y/N]: n
[07:18:58 WARNING] skipping 'https://wordpress.org/plugins/insert-php/+pagina.php?go='...
[07:18:58 PROMPT] would you like to process found URL: 'http://php.net/manual/en/function.header.php'[y/N]: n
[07:18:59 WARNING] skipping 'http://php.net/manual/en/function.header.php'...
[07:18:59 PROMPT] would you like to process found URL: 'https://stackoverflow.com/questions/768431/how-to-make-a-redirect-in-php'[y/N]: n
[07:18:59 WARNING] skipping 'https://stackoverflow.com/questions/768431/how-to-make-a-redirect-in-php'...
[07:18:59 PROMPT] would you like to process found URL: 'https://www.owasp.org/'[y/N]: n
[07:19:00 WARNING] skipping 'https://www.owasp.org/'...
[07:19:00 PROMPT] would you like to process found URL: 'http://php.net/manual/en/tutorial.firstpage.php'[y/N]: n
[07:19:00 WARNING] skipping 'http://php.net/manual/en/tutorial.firstpage.php'...


[*] shutting down at 07:19:00..


baal@baal-Aspire-5733Z:~/bin/python/zeus-scanner$ 
```

**Comment by Ekultek** [comment] 2017-10-11 19:57
Can't reproduce, so closing.

**Closed by Ekultek** 2017-10-11 19:57 UTC
Labels: unreproducable
