### ISSUE TITLE
Unhandled exception (bGoyyEe)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#253] opened 2017-12-07 00:18 UTC
Zeus version:
`1.4.2.4e0945`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 229, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 265, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='oldky.kgeu.org', port=80): Max retries exceeded with url: /%0A?Connection=close&X-Forwarded-For=6.13.30.81%2C+113.236.136.13%2C+134.3.17.214&User-Agent=Mozilla%2F5.0+%28X11%3B+U%3B+Linux+i686%3B+lt-LT%3B+rv%3A1.6%29+Gecko%2F20051114+Firefox%2F1.5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f58326c7390>, 'Connection to oldk...
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:\"Test page for Apache Installation\" --verbose --batch -p --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 18:16:27,117;zeus-log;DEBUG;loading script 'accellion'...
2017-12-06 18:16:27,117;zeus-log;DEBUG;loading script 'rssfeed'...
2017-12-06 18:16:27,118;zeus-log;DEBUG;loading script '4images'...
2017-12-06 18:16:27,118;zeus-log;DEBUG;loading script 'openxchange'...
2017-12-06 18:16:27,119;zeus-log;WARNING;no known plugins identified on target...
2017-12-06 18:16:27,119;zeus-log;DEBUG;loading XML data...
2017-12-06 18:16:27,120;zeus-log;INFO;attempting to get request headers for 'https://server.4mlinux.com/index.htm'...
2017-12-06 18:16:27,120;zeus-log;INFO;found a request cookie, saving to file...
2017-12-06 18:16:27,137;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/server.4mlinux.com(1).log'...
2017-12-06 18:16:27,137;zeus-log;DEBUG;fetched {'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Set-Cookie': '__cfduid=ddf243154694ad19a4ea673d1926977de1512605785; expires=Fri, 07-Dec-18 00:16:25 GMT; path=/; domain=.4mlinux.com; HttpOnly', 'Server': 'cloudflare-nginx', 'Connection': 'keep-alive', 'Date': 'Thu, 07 Dec 2017 00:16:26 GMT', 'CF-RAY': '3c934bd25c5a9336-SJC', 'Content-Type': 'text/html; charset=iso-8859-1'}...
2017-12-06 18:16:27,138;zeus-log;INFO;writing found headers to log file...
2017-12-06 18:16:27,140;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/server.4mlinux.com(1).json'...
2017-12-06 18:16:27,141;zeus-log;INFO;creating arguments for nmap...
2017-12-06 18:16:27,141;zeus-log;WARNING;if the port scan is not completed in 02:00(m) it will timeout...
2017-12-06 18:16:27,141;zeus-log;INFO;attempting to find IP address for hostname 'server.4mlinux.com'...
2017-12-06 18:16:27,142;zeus-log;DEBUG;checking for nmap on your system...
2017-12-06 18:16:27,142;zeus-log;DEBUG;nmap has been found under '/usr/local/bin/nmap'...
2017-12-06 18:16:27,142;zeus-log;INFO;starting port scan on IP address '104.28.9.32'...
2017-12-06 18:18:27,141;zeus-log;ERROR;port scan is taking to long and has hit the timeout, you can increase this time by passing the --time-sec flag (IE --time-sec 300)...
2017-12-06 18:18:27,142;zeus-log;INFO;currently running on 'http://oldky.kgeu.org/' (target #8)...
2017-12-06 18:18:27,142;zeus-log;INFO;fetching target meta-data...
2017-12-06 18:18:27,143;zeus-log;INFO;random IP address generated for header '6.13.30.81'...
2017-12-06 18:18:27,143;zeus-log;INFO;random IP address generated for header '113.236.136.13'...
2017-12-06 18:18:27,143;zeus-log;INFO;random IP address generated for header '134.3.17.214'...
2017-12-06 18:18:47,169;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'HTTPConnectionPool(host='oldky.kgeu.org', port=80): Max retries exceeded with url: /%0A?Connection=close&X-Forwarded-For=6.13.30.81%2C+113.236.136.13%2C+134.3.17.214&User-Agent=Mozilla%2F5.0+%28X11%3B+U%3B+Linux+i686%3B+lt-LT%3B+rv%3A1.6%29+Gecko%2F20051114+Firefox%2F1.5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f58326c7390>, 'Connection to oldky.kgeu.org timed out. (connect timeout=20)'))'...
Traceback (most recent call last):
  File "zeus.py", line 229, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 265, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='oldky.kgeu.org', port=80): Max retries exceeded with url: /%0A?Connection=close&X-Forwarded-For=6.13.30.81%2C+113.236.136.13%2C+134.3.17.214&User-Agent=Mozilla%2F5.0+%28X11%3B+U%3B+Linux+i686%3B+lt-LT%3B+rv%3A1.6%29+Gecko%2F20051114+Firefox%2F1.5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f58326c7390>, 'Connection to oldky.kgeu.org timed out. (connect timeout=20)'))

2017-12-06 18:18:47,640;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-06 18:18:47,641;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-06 18:18:47,658;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-06 18:18:47,658;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-12-07 02:40
duplicate of #245

**Closed by Ekultek** 2017-12-07 02:40 UTC
Labels: duplicate
