### ISSUE TITLE
Unhandled exception (ePtZgOm)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#268] opened 2017-12-07 05:37 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Network Camera NetworkCamera" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:37:34,597;zeus-log;DEBUG;loading script 'clipbucket'
2017-12-06 23:37:34,601;zeus-log;DEBUG;loading script 'ihtml'
2017-12-06 23:37:34,604;zeus-log;DEBUG;loading script '360'
2017-12-06 23:37:34,607;zeus-log;DEBUG;loading script '3dcart'
2017-12-06 23:37:34,609;zeus-log;DEBUG;loading script 'b2evolution'
2017-12-06 23:37:34,614;zeus-log;DEBUG;loading script 'bmcremedy'
2017-12-06 23:37:34,615;zeus-log;DEBUG;loading script 'abyss'
2017-12-06 23:37:34,616;zeus-log;DEBUG;loading script '68classified'
2017-12-06 23:37:34,618;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:37:34,622;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:37:34,624;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:37:34,625;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:37:34,628;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:37:34,631;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:37:34,637;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:37:34,641;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:37:34,644;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:37:34,648;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:37:34,649;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:37:34,651;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:37:34,654;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:37:34,657;zeus-log;INFO;possible plugin identified as 'JQuery'
2017-12-06 23:37:34,657;zeus-log;INFO;possible plugin identified as 'Open-Graph-Protocol'
2017-12-06 23:37:34,657;zeus-log;DEBUG;loading XML data
2017-12-06 23:37:34,660;zeus-log;INFO;attempting to get request headers for 'https://uk.reuters.com/article/brief-leovegas-invests-in-the-leading-st/brief-leovegas-invests-in-the-leading-streaming-network-casinogrounds-idUKFWN1O60PR'
2017-12-06 23:37:34,660;zeus-log;DEBUG;fetched {'Content-Length': '10503', 'Via': '1.1 48caa39e1bf7b421aefe9f98b0ab696b.cloudfront.net (CloudFront)', 'X-Cache': 'Error from cloudfront', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Server': 'nginx', 'Connection': 'keep-alive', 'X-Amz-Cf-Id': 'BIsmIiib8JSNk_ggW5R7l3-K4PW2Jrz5qR2DumqegQS75RJXPk-qVw==', 'Last-UpdatedL': 'Thu, 07 Dec 2017 05:29:34 GMT', 'Date': 'Thu, 07 Dec 2017 05:37:34 GMT', 'Content-Type': 'text/html;charset=UTF-8'}
2017-12-06 23:37:34,660;zeus-log;INFO;writing found headers to log file
2017-12-06 23:37:34,677;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/uk.reuters.com(2).json'
2017-12-06 23:37:34,678;zeus-log;INFO;searching a total of 5 pages of Gists for 'uk.reuters.com'
2017-12-06 23:37:34,678;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:37:35,216;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:37:35,773;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:37:36,608;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:37:37,145;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:37:37,680;zeus-log;DEBUG;found a total of 53 links to search
2017-12-06 23:37:38,344;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rajegannathan/222d72698580c2e9b2bdbf2cc887c12d/raw/badbb7146de1bb73a72af49a14f6bbec9bbd9d65/racist-ai.ipynb'
2017-12-06 23:37:39,687;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/debashisbarman/f2a708ff8fb8e9a68463ea014e73b062/raw/6553c03d8632dfe021114e74019e7f4dd3e93849/package.json'
2017-12-06 23:37:40,830;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/d14a2f9a72c2d721745992b56bc53d11/raw/6569bf2cfbe63f7dd7de177f1bc042754288e52b/brlog.trunk-test.20171207-142233'
2017-12-06 23:37:42,186;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/499940e908907614cff8f076937be6c2/raw/42294004b447d32f843d6ebd11f5d89dc6a95489/brlog.trunk-test.20171207-143132'
2017-12-06 23:37:43,489;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/eb5258165c582ded1c8328438e4b7f6b/raw/059a54383f2781763f91892b690ac8bb0f08eb1a/brlog.trunk-test.20171207-143100'
2017-12-06 23:37:45,048;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:37:45,279;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:37:45,280;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:37:45,280;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:37:45,281;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:20
duplicate of #256

**Closed** 2017-12-07 13:20 UTC
Labels: duplicate
