### ISSUE TITLE
ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //tajs.qq.com:16992/index.htm (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xf2c2f570>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#96] opened 2017-10-14 08:58 UTC
Zeus version:
`1.0.46`

Firefox version:
``

Error info:
```Traceback (most recent call last):
  File "/home/Scanner/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 101, in main_intel_amt
    json_data = __get_hardware(url, agent=agent, proxy=proxy)
  File "/home/Scanner/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 59, in __get_hardware
    req = __get_raw_data(target, 'hw-sys', agent=agent, proxy=proxy)
  File "/home/Scanner/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 51, in __get_raw_data
    'Authorization': __get_auth_headers(target),
  File "/home/Scanner/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 22, in __get_auth_headers
    }, proxies=proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //tajs.qq.com:16992/index.htm (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xf2c2f570>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
````

Running details:
`Linux-3.18.31-perf-g0bf156d-00991-gb62734d-aarch64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py -i -b http://oneday.qq.com/admin/nologin`

Log file info:
```2017-10-14 08:58:48,324;zeus-log;INFO;log file being saved to '/home/Scanner/Zeus-Scanner/log/zeus-log-1.log'...
2017-10-14 08:58:48,325;zeus-log;INFO;using default search engine...
2017-10-14 08:58:48,326;zeus-log;INFO;starting blackwidow on 'http://oneday.qq.com/admin/nologin'...
2017-10-14 08:58:48,683;zeus-log;INFO;successfully wrote found items to '/home/Scanner/Zeus-Scanner/log/blackwidow-log/blackwidow-log-1.log'...
2017-10-14 08:58:53,186;zeus-log;INFO;attempting to connect to 'http://tajs.qq.com' and get hardware info...
2017-10-14 08:58:53,186;zeus-log;INFO;getting raw information...
2017-10-14 08:58:53,186;zeus-log;INFO;header value not established, attempting to get bypass...
2017-10-14 08:58:53,197;zeus-log;ERROR;ran into exception 'HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //tajs.qq.com:16992/index.htm (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xf2c2f570>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))', cannot continue...
Traceback (most recent call last):
  File "/home/Scanner/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 101, in main_intel_amt
    json_data = __get_hardware(url, agent=agent, proxy=proxy)
  File "/home/Scanner/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 59, in __get_hardware
    req = __get_raw_data(target, 'hw-sys', agent=agent, proxy=proxy)
  File "/home/Scanner/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 51, in __get_raw_data
    'Authorization': __get_auth_headers(target),
  File "/home/Scanner/Zeus-Scanner/lib/attacks/intel_me/__init__.py", line 22, in __get_auth_headers
    }, proxies=proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //tajs.qq.com:16992/index.htm (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xf2c2f570>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))

2017-10-14 08:58:56,146;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-14 08:58:56,146;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-14 08:58:56,149;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-14 08:58:56,149;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-10-14 12:23
Duplicate of #97

**Closed by Ekultek** 2017-10-14 12:23 UTC
Labels: duplicate
