### ISSUE TITLE
Unhandled exception (mUzPyzu)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#311] opened 2017-12-17 11:11 UTC
Zeus version:
`1.4.11.b0ea07`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/root/Zeus-Scanner/var/search/selenium_search.py", line 264, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/Zeus-Scanner/var/search/selenium_search.py", line 106, in get_urls
    browser.execute_script("document.querySelectorAll('label.boxed')[1].click()")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 532, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: TypeError: document.querySelectorAll(...)[1] is undefined
```

Running details:
`Linux-4.12.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py -d .php?id=`

Log file info:
```2017-12-17 11:11:10,749;zeus-log;INFO;log file being saved to '/root/Zeus-Scanner/log/zeus-log-4.log'
2017-12-17 11:11:10,749;zeus-log;INFO;using default search engine
2017-12-17 11:11:10,749;zeus-log;INFO;starting dork scan with query '.php?id='
2017-12-17 11:11:10,750;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)
2017-12-17 11:11:10,750;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
2017-12-17 11:11:10,750;zeus-log;INFO;attempting to gather query URL
2017-12-17 11:11:10,750;zeus-log;INFO;setting up virtual display to hide the browser
2017-12-17 11:11:10,893;zeus-log;INFO;setting the browser
2017-12-17 11:11:17,338;zeus-log;INFO;browser will open shortly
2017-12-17 11:11:19,818;zeus-log;INFO;searching search engine using query '.php?id='
2017-12-17 11:11:19,961;zeus-log;ERROR;[7;31;31mselenium_search.pyc failed to gather the URL from search engine, caught exception 'Message: TypeError: document.querySelectorAll(...)[1] is undefined' exception has been logged to current log file
Traceback (most recent call last):
  File "/root/Zeus-Scanner/var/search/selenium_search.py", line 264, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/Zeus-Scanner/var/search/selenium_search.py", line 106, in get_urls
    browser.execute_script("document.querySelectorAll('label.boxed')[1].click()")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 532, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: TypeError: document.querySelectorAll(...)[1] is undefined


2017-12-17 11:11:26,027;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-17 11:11:26,027;zeus-log;INFO;[32mgetting authorization[0m
2017-12-17 11:11:26,028;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-17 11:11:26,029;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-19 15:19
Dupe of #312

**Closed by Ekultek** 2017-12-19 15:19 UTC
Labels: duplicate
