### ISSUE TITLE
InvalidProxyType: [socks5]192.228.247.141:59500 is not a valid proxy type, you might be looking for [].. (PolHkyn)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#121] opened 2017-10-22 21:22 UTC
Zeus version:
`1.0.57.977564`

Firefox version:
`(52, 4)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 552, in <module>
    agent=agent_to_use, pull_all=opt.noExclude, parse_webcache=opt.parseWebcache
  File "/root/Zeus-Scanner/var/google_search/search.py", line 246, in parse_search_results
    proxy_string = proxy_string_to_dict(proxy_string)
  File "/root/Zeus-Scanner/lib/core/settings.py", line 239, in proxy_string_to_dict
    proxy_data = get_proxy_type(proxy_string)
  File "/root/Zeus-Scanner/lib/core/settings.py", line 227, in get_proxy_type
    "{}..".format(prox_list[0], difflib.get_close_matches(prox_list[0], acceptable))
InvalidProxyType: [socks5]192.228.247.141:59500 is not a valid proxy type, you might be looking for []..
````

Running details:
`Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py --random-agent -l /root/Desktop/Queue.txt --proxy [socks5]192.228.247.141:59500 -s -B`

Log file info:
```2017-10-22 17:22:44,195;zeus-log;INFO;log file being saved to '/root/Zeus-Scanner/log/zeus-log-90.log'...
2017-10-22 17:22:44,196;zeus-log;INFO;specified to use non-default search engine...
2017-10-22 17:22:44,196;zeus-log;INFO;starting dork scan with query 'inurl:product-item.php?id='...
2017-10-22 17:22:44,196;zeus-log;WARNING;will not parse webcache URLs...
2017-10-22 17:22:44,196;zeus-log;WARNING;only pulling URLs with GET(query) parameters...
2017-10-22 17:22:44,197;zeus-log;ERROR;[7;31;31mran into exception '[socks5]192.228.247.141:59500 is not a valid proxy type, you might be looking for []..'...
Traceback (most recent call last):
  File "zeus.py", line 552, in <module>
    agent=agent_to_use, pull_all=opt.noExclude, parse_webcache=opt.parseWebcache
  File "/root/Zeus-Scanner/var/google_search/search.py", line 246, in parse_search_results
    proxy_string = proxy_string_to_dict(proxy_string)
  File "/root/Zeus-Scanner/lib/core/settings.py", line 239, in proxy_string_to_dict
    proxy_data = get_proxy_type(proxy_string)
  File "/root/Zeus-Scanner/lib/core/settings.py", line 227, in get_proxy_type
    "{}..".format(prox_list[0], difflib.get_close_matches(prox_list[0], acceptable))
InvalidProxyType: [socks5]192.228.247.141:59500 is not a valid proxy type, you might be looking for []..

2017-10-22 17:22:47,064;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-22 17:22:47,064;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-22 17:22:47,066;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-22 17:22:47,066;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-10-22 21:54
duplicate of #118

**Closed by Ekultek** 2017-10-22 21:54 UTC
Labels: duplicate
