### ISSUE TITLE
Unhandled exception (ErMKvgn)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#208] opened 2017-12-01 18:30 UTC
Zeus version:
`1.3.11.083e54`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 998, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 261, in main
    check_for_admin_page(url, extensions, show_possibles=show, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 140, in check_for_admin_page
    if int(data[2]) == error_code:
ValueError: invalid literal for int() with base 10: '404:'
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:\"Test page for Apache Installation\" --verbose --batch -a --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -M -L 10`

Log file info:
```2017-12-01 12:30:16,347;zeus-log;DEBUG;loading script 'squid'...
2017-12-01 12:30:16,348;zeus-log;DEBUG;loading script 'wallarm'...
2017-12-01 12:30:16,349;zeus-log;DEBUG;loading script 'yunsuo'...
2017-12-01 12:30:16,350;zeus-log;DEBUG;loading script 'bigip'...
2017-12-01 12:30:16,351;zeus-log;DEBUG;loading script 'anquanbao'...
2017-12-01 12:30:16,352;zeus-log;DEBUG;loading script 'generic'...
2017-12-01 12:30:16,353;zeus-log;INFO;no WAF/IDS/IPS has been identified on target URL...
2017-12-01 12:30:16,353;zeus-log;DEBUG;loading XML data...
2017-12-01 12:30:16,384;zeus-log;INFO;attempting to get request headers for 'http://we.ru/'...
2017-12-01 12:30:16,385;zeus-log;INFO;random IP address generated for header '21.59.156.138'...
2017-12-01 12:30:16,385;zeus-log;INFO;random IP address generated for header '246.5.235.9'...
2017-12-01 12:30:16,385;zeus-log;INFO;random IP address generated for header '139.164.131.91'...
2017-12-01 12:30:16,796;zeus-log;DEBUG;fetched {'Transfer-Encoding': 'chunked', 'Vary': 'accept-charset, user-agent', 'Keep-Alive': 'timeout=15, max=99', 'Server': 'Apache', 'Connection': 'Keep-Alive', 'Date': 'Fri, 01 Dec 2017 18:30:16 GMT', 'Content-Type': 'text/html; charset=windows-1251'}...
2017-12-01 12:30:16,797;zeus-log;INFO;writing found headers to log file...
2017-12-01 12:30:16,799;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/we.ru(1).json'...
2017-12-01 12:30:16,801;zeus-log;INFO;parsing robots.txt...
2017-12-01 12:30:17,242;zeus-log;ERROR;unable to connect to 'http://we.ru/robots.txt', assuming does not exist and continuing...
2017-12-01 12:30:17,242;zeus-log;WARNING;seems like this page is either blocking access to robots.txt or it does not exist...
2017-12-01 12:30:17,243;zeus-log;INFO;checking for a sitemap...
2017-12-01 12:30:17,632;zeus-log;ERROR;unable to connect to 'http://we.ru/sitemap.xml', assuming does not exist and continuing...
2017-12-01 12:30:17,633;zeus-log;INFO;loading extensions...
2017-12-01 12:30:17,660;zeus-log;DEBUG;loaded a total of 643 extensions...
2017-12-01 12:30:17,661;zeus-log;INFO;attempting to bruteforce admin panel...
2017-12-01 12:30:17,661;zeus-log;DEBUG;trying 'http://we.ru:23'...
2017-12-01 12:30:17,849;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:30:17,849;zeus-log;DEBUG;trying 'http://we.ru:82'...
2017-12-01 12:30:18,039;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:30:18,039;zeus-log;DEBUG;trying 'http://we.ru:2082'...
2017-12-01 12:30:18,239;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:30:18,239;zeus-log;DEBUG;trying 'http://we.ru:2083'...
2017-12-01 12:30:18,493;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:30:18,494;zeus-log;DEBUG;trying 'http://we.ru/administratie/'...
2017-12-01 12:30:18,893;zeus-log;ERROR;[7;31;31mran into exception 'invalid literal for int() with base 10: '404:'' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 998, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 261, in main
    check_for_admin_page(url, extensions, show_possibles=show, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 140, in check_for_admin_page
    if int(data[2]) == error_code:
ValueError: invalid literal for int() with base 10: '404:'

2017-12-01 12:30:19,413;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-01 12:30:19,413;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-01 12:30:19,431;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-01 12:30:19,432;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-12-01 18:43
duplicate of #207

**Closed by Ekultek** 2017-12-01 18:43 UTC
Labels: duplicate
