### ISSUE TITLE
Unhandled exception (jTsouoN)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#261] opened 2017-12-07 05:27 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle: "index of/root" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:27:00,684;zeus-log;DEBUG;loading script 'b2evolution'
2017-12-06 23:27:00,685;zeus-log;DEBUG;loading script 'bmcremedy'
2017-12-06 23:27:00,686;zeus-log;DEBUG;loading script 'abyss'
2017-12-06 23:27:00,686;zeus-log;DEBUG;loading script '68classified'
2017-12-06 23:27:00,687;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:27:00,688;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:27:00,688;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:27:00,689;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:27:00,690;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:27:00,690;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:27:00,691;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:27:00,692;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:27:00,692;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:27:00,693;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:27:00,693;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:27:00,694;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:27:00,695;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:27:00,696;zeus-log;WARNING;no known plugins identified on target
2017-12-06 23:27:00,696;zeus-log;DEBUG;loading XML data
2017-12-06 23:27:00,696;zeus-log;INFO;attempting to get request headers for 'http://jooh.no/root/pix/'
2017-12-06 23:27:00,697;zeus-log;DEBUG;fetched {'Date': 'Thu, 07 Dec 2017 05:26:59 GMT', 'Content-Length': '348', 'Content-Type': 'text/html', 'Connection': 'Close', 'Server': 'Abyss/2.11.6-X2-Win32 AbyssLib/2.11.6'}
2017-12-06 23:27:00,697;zeus-log;INFO;writing found headers to log file
2017-12-06 23:27:00,698;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/jooh.no(1).json'
2017-12-06 23:27:00,698;zeus-log;INFO;searching a total of 5 pages of Gists for 'jooh.no'
2017-12-06 23:27:00,699;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:27:01,293;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:27:01,780;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:27:02,497;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:27:03,039;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:27:03,564;zeus-log;DEBUG;found a total of 53 links to search
2017-12-06 23:27:04,138;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/x831617/3d434d22bad00b4aa6f89dd057006fe4/raw/6106e4bb52e6cf2e903851c2d5923f0465518852/gistfile1.txt'
2017-12-06 23:27:05,537;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/40536a74787c6c67119faa45220fe123/raw/5d6baf4c1a2f890bea59b1381a80bb662ff46931/brlog.trunk-test.20171207-142138'
2017-12-06 23:27:06,586;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/theatlasroom/b09c9ef74aec56858383a11b28b3f8df/raw/239b238f870c10dbb54027bbe2bbb9b2c545ebaf/glossing-over-ethereum.md'
2017-12-06 23:27:07,623;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/wynot/0889755e08ab42e2394f205aaa47c58e/raw/c3d39585aec8cc8caf7a990e49cacb3f5235b1e9/gistfile1.txt'
2017-12-06 23:27:08,945;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/bb98542f524d307378eb1327e23ceb6c/raw/80b9fbce9daa43d71a75187f62665db90b10c135/brlog.trunk-test.20171207-141639'
2017-12-06 23:27:12,087;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/nitinware/e611ff7caf61ddf62c6652c359df83e1/raw/a9df894b278261c426ce889854ec719e3e2923f8/temperature.json'
2017-12-06 23:27:13,224;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/81b9e8b51b34f729b6957d96812dce6e/raw/775fb73394951aea5bf8c74e6b1089235c6a39d5/brlog.trunk-test.20171207-141653'
2017-12-06 23:27:14,358;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/9fdb2a59ae754ccafbfa60eb42f5e4d5/raw/52f8b3e0e8d2d90d70f2c5df8bad6d7fd49822e4/brlog.trunk-test.20171207-141404'
2017-12-06 23:27:16,251;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/189c1d7c650564d04d42ee4f5316062f/raw/943a323617efa0932571330a19a71848ccfd30a3/brlog.trunk-test.20171207-142406'
2017-12-06 23:27:17,599;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/4f0a2cff9daa58772a7887351462baa5/raw/7905f04057048228e2a936631a7932d650c70ac2/brlog.trunk-test.20171207-141413'
2017-12-06 23:27:19,861;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:27:19,986;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:27:19,986;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:27:19,987;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:27:19,988;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:18
duplicate of #256

**Closed** 2017-12-07 13:18 UTC
Labels: duplicate
