### ISSUE TITLE
Unhandled exception (PwNJGGf)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#277] opened 2017-12-07 05:40 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Network Camera NetworkCamera" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:39:43,355;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:39:43,862;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:39:44,371;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:39:44,924;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:39:45,484;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:39:46,244;zeus-log;DEBUG;found a total of 53 links to search
2017-12-06 23:39:46,827;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rajegannathan/222d72698580c2e9b2bdbf2cc887c12d/raw/badbb7146de1bb73a72af49a14f6bbec9bbd9d65/racist-ai.ipynb'
2017-12-06 23:39:47,937;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/debashisbarman/f2a708ff8fb8e9a68463ea014e73b062/raw/4a1b37990daaae58d49aa454ec79497141eee61c/init.coffee'
2017-12-06 23:39:49,165;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/d14a2f9a72c2d721745992b56bc53d11/raw/6569bf2cfbe63f7dd7de177f1bc042754288e52b/brlog.trunk-test.20171207-142233'
2017-12-06 23:39:50,542;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/499940e908907614cff8f076937be6c2/raw/42294004b447d32f843d6ebd11f5d89dc6a95489/brlog.trunk-test.20171207-143132'
2017-12-06 23:39:51,811;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/eb5258165c582ded1c8328438e4b7f6b/raw/059a54383f2781763f91892b690ac8bb0f08eb1a/brlog.trunk-test.20171207-143100'
2017-12-06 23:39:53,215;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/10046fb2d7e63a69f9f5e73ecfb8e9d5/raw/456a6911d4ae0fc09016075c87f466353bd1aa17/brlog.trunk-test.20171207-142811'
2017-12-06 23:39:54,242;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/Gigacore/9665b5de48ade170909a2790effce02d/raw/01f6aa40a057ca20e9130582660347c2ebcfee7b/rest_operator.js'
2017-12-06 23:39:55,269;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/fabiovella83/a3bbb8ade758a398a12389a98523ebab/raw/239b238f870c10dbb54027bbe2bbb9b2c545ebaf/glossing-over-ethereum.md'
2017-12-06 23:39:56,386;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/lpabon/4455490478d01419eaf438675e134438/raw/09c623fdd8bce073b3b7f8738ef5d1596ec64d3d/csi-questions.md'
2017-12-06 23:39:57,554;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ketankr9/2f66ec77533851f6e4afcde80bae5536/raw/dc116108298a2c3d1968bb146110806cc01af23c/autoSSHlogin.sh'
2017-12-06 23:39:59,499;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/071754f16d5c51c418bdc2a78508b666/raw/2088c623f315e61203bc68fab5dead3161cd18f5/brlog.trunk-test.20171207-143639'
2017-12-06 23:40:00,548;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/jorgerodriguez434/5946f0ca1f4f437ee1bd91b045c7cdf8/raw/1cf1490bfb40836ba37a94452df53167f73c7c5e/jQuery%2520Walkthroughs'
2017-12-06 23:40:01,737;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/theatlasroom/b09c9ef74aec56858383a11b28b3f8df/raw/239b238f870c10dbb54027bbe2bbb9b2c545ebaf/glossing-over-ethereum.md'
2017-12-06 23:40:03,126;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/4453fef558360556ff8806a02a8eca9d/raw/b4c79129e81f3319c41b8a2da15ef711496e430d/brlog.trunk-test.20171207-142522'
2017-12-06 23:40:04,626;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/openpanzer/447c63020a42ec07e1d7563ec5da4bd7/raw/a677ec9eab958758eca29d3b6762df8a5a572e08/openpanzer-save.json'
2017-12-06 23:40:05,843;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/mdub/3aa24e890e7e6d4ba8b08cb99a9b4c7d/raw/4854a1312f4355727ea0ff48789db9de1a2cf648/.gitconfig'
2017-12-06 23:40:06,943;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rustywoman/9a49077ad20618d496c5213ef95d7161/raw/50628d9ab9249e17c9a2805a62c0fe2665a69196/client.js'
2017-12-06 23:40:08,283;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/7d0a79690f3b2c18a03c38d3fc962102/raw/ee053f7c561b020f8e99a1324724ad397331b21e/brlog.trunk-test.20171207-142905'
2017-12-06 23:40:09,684;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/tsingyi/1b0e0e7381c511831078b326d1f70a08/raw/954a82038044662f0d5ae97ddd2d17ace313db78/the_choosed_one.py'
2017-12-06 23:40:10,750;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/arturmarkovv/81d220e3b398425a989c73913eb4f265/raw/373e445e1a575f235d29f064f0989789fb243f9b/2.2'
2017-12-06 23:40:11,798;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/tlawal/97eb7a5c649680bf691c39a018196d97/raw/eadebc3744f9fb9b3f1cc7cce0815efdaea864fa/miner.html.erb'
2017-12-06 23:40:13,370;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/josephhernandez20/b532aaacc327cd98007672d9bff8143b/raw/71d8178d900bdaa957cde043fe4c257a9fdd670a/LinkedList.cpp'
2017-12-06 23:40:14,707;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/cwitch1/d54dddfe4a8f605122dbab74b699d5f4/raw/87375d0acf26d4a108e36b51853db9abff18af6d/Prac%2520Fin%25203.cpp'
2017-12-06 23:40:16,005;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/d259ea4edfdc6990b42d2314b8e8773e/raw/c31e87935f847e641c3b816b83a9502b1e0a9a88/brlog.trunk-test.20171207-143626'
2017-12-06 23:40:17,388;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/0dfe017bd55bcd7b5c5600fd959d3632/raw/ad23e52576122e6dbee98fd65d667963633d18f1/brlog.trunk-test.20171207-144120'
2017-12-06 23:40:18,848;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rustywoman/37968987b3435e519c50f83fcdd3033d/raw/d924d7266236c89725a8ae43919a65f3bbe3eb3a/client.js'
2017-12-06 23:40:20,757;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/Kasu/71feb95489c2d5dcfd446de20875e1d3/raw/3634099d1ae966a88cc5380e5429cc0b6d95e97e/tsconfig.json'
2017-12-06 23:40:21,850;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/tannerkrewson/2784deab60961878ca420e37f397ec85/raw/4dcb00b98b42e4ec09fb8775afa1e7cf654876cb/rational_runner.cc'
2017-12-06 23:40:23,079;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/gt515ru/331f28bc65d570ab3e955a92c04ebfdf/raw/5a5ad8a5a45e9ffa1380a870217bf89ed8b8968d/gistfile1.txt'
2017-12-06 23:40:24,231;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/codepen24/eca67227fbf147d9bad4566a045cf42f/raw/934aed62ec0b36e04da05a45dee5c66a54fb3804/checkbox.markdown'
2017-12-06 23:40:25,370;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/qsLI/ccd136dbe0dcc2fd382a626662add8fc/raw/ebffd264f5022c69f86d15a44c9d0f634642bec4/memcached.sh'
2017-12-06 23:40:26,697;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/989c7e6c453d883c8ab1cce3142f3d61/raw/5c4a685f78483e3681fb03f0facd6e18b5cf1201/brlog.trunk-test.20171207-143853'
2017-12-06 23:40:27,924;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/HugsLibRecordKeeper/798836ed465edfb6305f844e05d190a2/raw/221d1b3796c6b9fa3d88c8a5aecc216efd8ec9e5/output_log.txt'
2017-12-06 23:40:29,198;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/e7ea250d224a2984f118dd8abfb20cc9/raw/2d72c1a8f6a17af4b8415592e586999c2fca3c0f/brlog.trunk-test.20171207-142637'
2017-12-06 23:40:31,344;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:40:31,528;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:40:31,528;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:40:31,529;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:40:31,534;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:23
duplicate of #256

**Closed** 2017-12-07 13:24 UTC
Labels: duplicate
