### ISSUE TITLE
Unhandled exception (znoxtjp)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#275] opened 2017-12-07 05:39 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Network Camera NetworkCamera" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:39:16,148;zeus-log;DEBUG;loading script 'b2evolution'
2017-12-06 23:39:16,151;zeus-log;DEBUG;loading script 'bmcremedy'
2017-12-06 23:39:16,153;zeus-log;DEBUG;loading script 'abyss'
2017-12-06 23:39:16,153;zeus-log;DEBUG;loading script '68classified'
2017-12-06 23:39:16,155;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:39:16,157;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:39:16,159;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:39:16,159;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:39:16,161;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:39:16,163;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:39:16,167;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:39:16,170;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:39:16,171;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:39:16,174;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:39:16,175;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:39:16,175;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:39:16,177;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:39:16,179;zeus-log;INFO;possible plugin identified as 'JQuery'
2017-12-06 23:39:16,179;zeus-log;INFO;possible plugin identified as 'Open-Graph-Protocol'
2017-12-06 23:39:16,180;zeus-log;INFO;possible plugin identified as 'Google API'
2017-12-06 23:39:16,180;zeus-log;INFO;possible plugin identified as 'RSS Feed'
2017-12-06 23:39:16,180;zeus-log;DEBUG;loading XML data
2017-12-06 23:39:16,180;zeus-log;INFO;attempting to get request headers for 'http://www.ilovepage1.com/blog/allintitle-network-camera-networkcamera'
2017-12-06 23:39:16,181;zeus-log;INFO;found a request cookie, saving to file
2017-12-06 23:39:16,182;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.ilovepage1.com-cookie.log'
2017-12-06 23:39:16,182;zeus-log;DEBUG;fetched {'X-Host': 'pages3.sf2p.intern.weebly.net', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Set-Cookie': '__cfduid=d4904d980297e3cc4d717d2a10ab92d731512625155; expires=Fri, 07-Dec-18 05:39:15 GMT; path=/; domain=.ilovepage1.com; HttpOnly, language=en; expires=Thu, 21-Dec-2017 05:39:15 GMT; Max-Age=1209600; path=/', 'Vary': 'User-Agent', 'Server': 'cloudflare-nginx', 'Connection': 'keep-alive', 'X-UA-Compatible': 'IE=edge,chrome=1', 'Cache-Control': 'private', 'Date': 'Thu, 07 Dec 2017 05:39:15 GMT', 'CF-RAY': '3c9524b7d5b295ef-SJC', 'Content-Type': 'text/html; charset=UTF-8'}
2017-12-06 23:39:16,182;zeus-log;INFO;writing found headers to log file
2017-12-06 23:39:16,183;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.ilovepage1.com-headers.json'
2017-12-06 23:39:16,183;zeus-log;INFO;searching a total of 5 pages of Gists for 'www.ilovepage1.com'
2017-12-06 23:39:16,183;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:39:16,651;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:39:17,184;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:39:17,699;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:39:18,201;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:39:18,806;zeus-log;DEBUG;found a total of 53 links to search
2017-12-06 23:39:19,440;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rajegannathan/222d72698580c2e9b2bdbf2cc887c12d/raw/badbb7146de1bb73a72af49a14f6bbec9bbd9d65/racist-ai.ipynb'
2017-12-06 23:39:20,529;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/debashisbarman/f2a708ff8fb8e9a68463ea014e73b062/raw/4a1b37990daaae58d49aa454ec79497141eee61c/init.coffee'
2017-12-06 23:39:21,622;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/d14a2f9a72c2d721745992b56bc53d11/raw/6569bf2cfbe63f7dd7de177f1bc042754288e52b/brlog.trunk-test.20171207-142233'
2017-12-06 23:39:23,243;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/499940e908907614cff8f076937be6c2/raw/42294004b447d32f843d6ebd11f5d89dc6a95489/brlog.trunk-test.20171207-143132'
2017-12-06 23:39:24,443;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/eb5258165c582ded1c8328438e4b7f6b/raw/059a54383f2781763f91892b690ac8bb0f08eb1a/brlog.trunk-test.20171207-143100'
2017-12-06 23:39:25,835;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:39:25,965;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:39:25,965;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:39:25,966;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:39:25,966;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:23
duplicate of #256

**Closed** 2017-12-07 13:24 UTC
Labels: duplicate
