### ISSUE TITLE
Unhandled exception (QcycLqm)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#303] opened 2017-12-11 20:40 UTC
Zeus version:
`1.4.8.73a645`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 189, in <module>
    __run_attacks_main()
  File "zeus.py", line 140, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1007, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 216, in main
    results = check_for_externals(url, robots=True, batch=batch)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 44, in check_for_externals
    _, code, data, _ = lib.core.common.get_page(full_url)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 382, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
InvalidURL: Invalid URL u'http:///robots.txt': No host supplied
```

Running details:
`Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:template.php?opcion= --verbose --batch -a --x-forward --random-agent -W -E --identify-waf --identify-plugins`

Log file info:
```2017-12-11 14:39:51,356;zeus-log;INFO;creating connection tree
2017-12-11 14:39:51,356;zeus-log;WARNING;only writing successful connections to log file
2017-12-11 14:39:51,357;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/admin-page-log/www.todoexpertos.com-admin-page.log'
2017-12-11 14:39:51,358;zeus-log;INFO;currently running on 'http://' (target #10)
2017-12-11 14:39:51,358;zeus-log;INFO;fetching target meta-data
2017-12-11 14:39:51,358;zeus-log;INFO;random IP address generated for header '135.71.6.32'
2017-12-11 14:39:51,359;zeus-log;INFO;random IP address generated for header '31.200.220.248'
2017-12-11 14:39:51,359;zeus-log;INFO;random IP address generated for header '250.70.192.113'
2017-12-11 14:40:01,370;zeus-log;WARNING;target actively refused the connection, sleeping for 5s and retrying the request
2017-12-11 14:40:06,376;zeus-log;INFO;random IP address generated for header '132.40.3.211'
2017-12-11 14:40:06,376;zeus-log;INFO;random IP address generated for header '84.90.85.127'
2017-12-11 14:40:06,377;zeus-log;INFO;random IP address generated for header '166.63.181.13'
2017-12-11 14:40:16,388;zeus-log;WARNING;target actively refused the connection, sleeping for 5s and retrying the request
2017-12-11 14:40:21,394;zeus-log;INFO;random IP address generated for header '43.134.120.9'
2017-12-11 14:40:21,395;zeus-log;INFO;random IP address generated for header '118.58.60.151'
2017-12-11 14:40:21,395;zeus-log;INFO;random IP address generated for header '156.44.94.54'
2017-12-11 14:40:31,409;zeus-log;ERROR;target is refusing to allow meta-data dumping, skipping
2017-12-11 14:40:31,409;zeus-log;INFO;parsing robots.txt
2017-12-11 14:40:31,411;zeus-log;ERROR;[7;31;31mURL provided is not valid, schema appears to be missing
Traceback (most recent call last):
  File "zeus.py", line 189, in <module>
    __run_attacks_main()
  File "zeus.py", line 140, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1007, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 216, in main
    results = check_for_externals(url, robots=True, batch=batch)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 44, in check_for_externals
    _, code, data, _ = lib.core.common.get_page(full_url)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 382, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
InvalidURL: Invalid URL u'http:///robots.txt': No host supplied

2017-12-11 14:40:32,081;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-11 14:40:32,081;zeus-log;INFO;[32mgetting authorization[0m
2017-12-11 14:40:32,214;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-11 14:40:32,219;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-12 02:57
dupe of #286

**Closed by Ekultek** 2017-12-12 02:57 UTC
Labels: duplicate
