### ISSUE TITLE
Unhandled exception (aSzFDoD)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#269] opened 2017-12-07 05:37 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Network Camera NetworkCamera" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:37:46,668;zeus-log;DEBUG;loading script 'ihtml'
2017-12-06 23:37:46,669;zeus-log;DEBUG;loading script '360'
2017-12-06 23:37:46,669;zeus-log;DEBUG;loading script '3dcart'
2017-12-06 23:37:46,670;zeus-log;DEBUG;loading script 'b2evolution'
2017-12-06 23:37:46,671;zeus-log;DEBUG;loading script 'bmcremedy'
2017-12-06 23:37:46,672;zeus-log;DEBUG;loading script 'abyss'
2017-12-06 23:37:46,673;zeus-log;DEBUG;loading script '68classified'
2017-12-06 23:37:46,673;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:37:46,674;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:37:46,675;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:37:46,675;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:37:46,676;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:37:46,676;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:37:46,677;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:37:46,678;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:37:46,679;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:37:46,679;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:37:46,680;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:37:46,680;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:37:46,681;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:37:46,682;zeus-log;WARNING;no known plugins identified on target
2017-12-06 23:37:46,682;zeus-log;DEBUG;loading XML data
2017-12-06 23:37:46,682;zeus-log;INFO;attempting to get request headers for 'http://akd.apnstatic.com/media/html/sr/en/privacy.html'
2017-12-06 23:37:46,683;zeus-log;INFO;found a request cookie, saving to file
2017-12-06 23:37:46,684;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/akd.apnstatic.com(10).log'
2017-12-06 23:37:46,684;zeus-log;DEBUG;fetched {'Content-Length': '192', 'Content-Encoding': 'gzip', 'Set-Cookie': 'lb_selected_pool=poolA0;expires=Fri, 08-Dec-2017 05:37:44 GMT;path=/;', 'Vary': 'Accept-Encoding', 'Server': 'Apache', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=31536000', 'Date': 'Thu, 07 Dec 2017 05:37:46 GMT', 'Content-Type': 'text/html; charset=iso-8859-1'}
2017-12-06 23:37:46,684;zeus-log;INFO;writing found headers to log file
2017-12-06 23:37:46,685;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/akd.apnstatic.com(10).json'
2017-12-06 23:37:46,685;zeus-log;INFO;searching a total of 5 pages of Gists for 'akd.apnstatic.com'
2017-12-06 23:37:46,686;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:37:47,198;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:37:47,711;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:37:48,287;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:37:48,840;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:37:49,378;zeus-log;DEBUG;found a total of 53 links to search
2017-12-06 23:37:50,180;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rajegannathan/222d72698580c2e9b2bdbf2cc887c12d/raw/badbb7146de1bb73a72af49a14f6bbec9bbd9d65/racist-ai.ipynb'
2017-12-06 23:37:51,145;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/debashisbarman/f2a708ff8fb8e9a68463ea014e73b062/raw/6553c03d8632dfe021114e74019e7f4dd3e93849/package.json'
2017-12-06 23:37:52,321;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/d14a2f9a72c2d721745992b56bc53d11/raw/6569bf2cfbe63f7dd7de177f1bc042754288e52b/brlog.trunk-test.20171207-142233'
2017-12-06 23:37:53,837;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/499940e908907614cff8f076937be6c2/raw/42294004b447d32f843d6ebd11f5d89dc6a95489/brlog.trunk-test.20171207-143132'
2017-12-06 23:37:55,014;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/eb5258165c582ded1c8328438e4b7f6b/raw/059a54383f2781763f91892b690ac8bb0f08eb1a/brlog.trunk-test.20171207-143100'
2017-12-06 23:37:56,388;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:37:56,544;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:37:56,544;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:37:56,545;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:37:56,545;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:21
duplicate of #256

**Closed** 2017-12-07 13:22 UTC
Labels: duplicate
