### ISSUE TITLE
Unhandled exception (XRRqIXN)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#276] opened 2017-12-07 05:39 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Network Camera NetworkCamera" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:39:33,678;zeus-log;DEBUG;loading script 'clipbucket'
2017-12-06 23:39:33,679;zeus-log;DEBUG;loading script 'ihtml'
2017-12-06 23:39:33,680;zeus-log;DEBUG;loading script '360'
2017-12-06 23:39:33,681;zeus-log;DEBUG;loading script '3dcart'
2017-12-06 23:39:33,682;zeus-log;DEBUG;loading script 'b2evolution'
2017-12-06 23:39:33,683;zeus-log;DEBUG;loading script 'bmcremedy'
2017-12-06 23:39:33,685;zeus-log;DEBUG;loading script 'abyss'
2017-12-06 23:39:33,686;zeus-log;DEBUG;loading script '68classified'
2017-12-06 23:39:33,687;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:39:33,688;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:39:33,688;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:39:33,689;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:39:33,690;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:39:33,690;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:39:33,691;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:39:33,692;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:39:33,692;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:39:33,693;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:39:33,693;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:39:33,694;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:39:33,695;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:39:33,696;zeus-log;WARNING;no known plugins identified on target
2017-12-06 23:39:33,696;zeus-log;DEBUG;loading XML data
2017-12-06 23:39:33,696;zeus-log;INFO;attempting to get request headers for 'http://honkaiida.miemasu.net/'
2017-12-06 23:39:33,697;zeus-log;DEBUG;fetched {}
2017-12-06 23:39:33,697;zeus-log;INFO;writing found headers to log file
2017-12-06 23:39:33,698;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/honkaiida.miemasu.net(1).json'
2017-12-06 23:39:33,698;zeus-log;INFO;searching a total of 5 pages of Gists for 'honkaiida.miemasu.net'
2017-12-06 23:39:33,698;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:39:34,199;zeus-log;WARNING;page #1 failed to load with status code 429 (reason 'to many requests')
2017-12-06 23:39:34,199;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:39:34,446;zeus-log;WARNING;page #2 failed to load with status code 429 (reason 'to many requests')
2017-12-06 23:39:34,447;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:39:34,702;zeus-log;WARNING;page #3 failed to load with status code 429 (reason 'to many requests')
2017-12-06 23:39:34,702;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:39:35,230;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:39:35,737;zeus-log;DEBUG;found a total of 23 links to search
2017-12-06 23:39:36,331;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rajegannathan/222d72698580c2e9b2bdbf2cc887c12d/raw/badbb7146de1bb73a72af49a14f6bbec9bbd9d65/racist-ai.ipynb'
2017-12-06 23:39:37,630;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/499940e908907614cff8f076937be6c2/raw/42294004b447d32f843d6ebd11f5d89dc6a95489/brlog.trunk-test.20171207-143132'
2017-12-06 23:39:38,927;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/10046fb2d7e63a69f9f5e73ecfb8e9d5/raw/456a6911d4ae0fc09016075c87f466353bd1aa17/brlog.trunk-test.20171207-142811'
2017-12-06 23:39:40,938;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:39:41,069;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:39:41,069;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:39:41,069;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:39:41,070;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:23
duplicate of #256

**Closed** 2017-12-07 13:24 UTC
Labels: duplicate
