### ISSUE TITLE
Unhandled exception (DjCNACM)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#280] opened 2017-12-07 05:42 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Network Camera NetworkCamera" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:42:03,927;zeus-log;DEBUG;loading script '3dcart'
2017-12-06 23:42:03,937;zeus-log;DEBUG;loading script 'b2evolution'
2017-12-06 23:42:03,961;zeus-log;DEBUG;loading script 'bmcremedy'
2017-12-06 23:42:03,963;zeus-log;DEBUG;loading script 'abyss'
2017-12-06 23:42:03,963;zeus-log;DEBUG;loading script '68classified'
2017-12-06 23:42:03,977;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:42:03,994;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:42:04,004;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:42:04,029;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:42:04,044;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:42:04,057;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:42:10,522;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:42:10,541;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:42:10,558;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:42:17,009;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:42:17,010;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:42:17,020;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:42:17,035;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:42:17,050;zeus-log;WARNING;no known plugins identified on target
2017-12-06 23:42:17,050;zeus-log;DEBUG;loading XML data
2017-12-06 23:42:17,051;zeus-log;INFO;attempting to get request headers for 'https://www.alibaba.com/showroom/ip-network-camera-networkcamera.html'
2017-12-06 23:42:17,052;zeus-log;INFO;found a request cookie, saving to file
2017-12-06 23:42:17,053;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.alibaba.com(1).log'
2017-12-06 23:42:17,053;zeus-log;DEBUG;fetched {'Content-Language': 'en-US', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'ali_apache_id=72.198.49.179.1512625323152.467369.6; path=/; domain=.alibaba.com; expires=Wed, 30-Nov-2084 01:01:01 GMT, JSESSIONID=EF6YE2J5P2-L4PQYPEFVUMGFD7V5EPQ1-18922WAJ-QVG1; Path=/; HttpOnly, ali_apache_track=; Domain=.alibaba.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, ali_apache_tracktmp=; Domain=.alibaba.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, xman_us_f=x_l=0; Domain=.alibaba.com; Expires=Tue, 25-Dec-2085 08:56:10 GMT; Path=/, acs_usuc_t=acs_rt=34ccf28430ba40a4be4bee90266a6e08; Domain=.alibaba.com; Path=/, xman_t=dv4DjnWkdO4jDcQUmhxQrUQ8+hEsAT0xMa41A2kdNvDgxIEqNVPyWT7+lGJens+B; Domain=.alibaba.com; Path=/; HttpOnly, xman_f=z770HJVT+yD5cW154XIET7y/10rO4IHW+qty7HVxThr0CaLQpCHgllYZWAogkpqylJOyJwe9cAsq3N+1T6AM5pU95Fvy7pTz2a+VBjR/UL4TEDAEE18CoA==; Domain=.alibaba.com; Expires=Tue, 25-Dec-2085 08:56:10 GMT; Path=/; HttpOnly, _mle_tmp0=eNrz4A12DQ729PeL9%2FV3cfUxiKnOTLFScnUzi3Q18jINMNL1MQkIjAxwdQsL9XV3czEPM3UNCDTUNbSwNDIKd%2FTSDQxzN1TSSS6xMjQ1NDIzMjU2MjY2NNZJTEYTyK2wMqiNAgBryxyW; Path=/; HttpOnly', 'Strict-Transport-Security': 'max-age=31536000', 'Vary': 'Accept-Encoding', 'Server': 'Apache-Coyote/1.1', 'Connection': 'keep-alive', 'Resin-Trace': 'ali_resin_trace=is_merge_supplier=0|ser=1007|pageId=c302edbbdf934ebdbf597743f4556768|set=3|is_escrow_filt=0|sn_cat_type=2|is_onsite_check=0|intro_help_disp=1|is_gs_filt=0|proxy_ip=0|searchweb_vm_style_group=new_version|beaconId=34ccf28430ba40a4be4bee90266a6e08|pvmi=c6c56275ad534631810bdc82e50ef28d|is_av_filt=0|sek_sepd=ip+network+camera+networkcamera|is_as_filt=0|is_f0_test=1|industry_id=301102|bran_ab_test=0|sq_type=a|isAtmOnline=0|kw_type=0|semi=0|se_rst=42|isGalleryList=1|se_pn=1|forecast_post_cate=301102:0:255|is_chinasuppliers=0|s_abtest=01_M_R|p4pid=363ef996-8e79-4200-8d77-6f18721e505d|sek=ip+network+camera+networkcamera', 'Date': 'Thu, 07 Dec 2017 05:42:03 GMT', 'P3P': 'CP="CAO PSA OUR"', 'Content-Type': 'text/html;charset=UTF-8'}
2017-12-06 23:42:17,053;zeus-log;WARNING;provided target has protection against unencrypted connections (force HTTPS connection)
2017-12-06 23:42:17,053;zeus-log;INFO;writing found headers to log file
2017-12-06 23:42:17,054;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.alibaba.com(1).json'
2017-12-06 23:42:17,055;zeus-log;INFO;searching a total of 5 pages of Gists for 'www.alibaba.com'
2017-12-06 23:42:17,055;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:42:17,681;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:42:18,223;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:42:18,719;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:42:19,197;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:42:19,716;zeus-log;DEBUG;found a total of 51 links to search
2017-12-06 23:42:20,539;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/debashisbarman/f2a708ff8fb8e9a68463ea014e73b062/raw/4a1b37990daaae58d49aa454ec79497141eee61c/init.coffee'
2017-12-06 23:42:21,716;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/e23862d0a7798eca4c6e227762b328d9/raw/e9b9ba08237f2a93580fbf4b6f3e015301328268/brlog.trunk-test.20171207-143929'
2017-12-06 23:42:23,074;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/499940e908907614cff8f076937be6c2/raw/42294004b447d32f843d6ebd11f5d89dc6a95489/brlog.trunk-test.20171207-143132'
2017-12-06 23:42:24,228;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/eb5258165c582ded1c8328438e4b7f6b/raw/059a54383f2781763f91892b690ac8bb0f08eb1a/brlog.trunk-test.20171207-143100'
2017-12-06 23:42:25,477;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/10046fb2d7e63a69f9f5e73ecfb8e9d5/raw/456a6911d4ae0fc09016075c87f466353bd1aa17/brlog.trunk-test.20171207-142811'
2017-12-06 23:42:26,758;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/Gigacore/9665b5de48ade170909a2790effce02d/raw/01f6aa40a057ca20e9130582660347c2ebcfee7b/rest_operator.js'
2017-12-06 23:42:27,999;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:42:28,169;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:42:28,169;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:42:28,169;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:42:28,170;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:24
duplicate of #256

**Closed** 2017-12-07 13:24 UTC
Labels: duplicate
