### ISSUE TITLE
Unhandled exception (NNtlWiT)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#267] opened 2017-12-07 05:29 UTC
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle: "index of/root" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:29:14,238;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:29:14,275;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:29:14,277;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:29:16,687;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:29:16,734;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:29:16,774;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:29:19,151;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:29:19,152;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:29:19,178;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:29:19,214;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:29:19,250;zeus-log;INFO;possible plugin identified as 'JQuery'
2017-12-06 23:29:19,250;zeus-log;INFO;possible plugin identified as 'Open-Graph-Protocol'
2017-12-06 23:29:19,251;zeus-log;INFO;possible plugin identified as 'HTML5'
2017-12-06 23:29:19,251;zeus-log;DEBUG;loading XML data
2017-12-06 23:29:19,251;zeus-log;INFO;attempting to get request headers for 'http://www.bbc.co.uk/go/newsFeedXML/moreover/-/sport/cricket/42195885'
2017-12-06 23:29:19,252;zeus-log;DEBUG;fetched {'X-PAL-Host': 'pal0101.back.live.cwwtf.local:80', 'Content-Length': '187946', 'Content-Language': 'en-gb', 'Content-Encoding': 'gzip', 'Content-Type': 'text/html', 'Accept-Ranges': 'bytes', 'Vary': 'X-CDN,Accept-Encoding', 'Server': 'Apache', 'Connection': 'keep-alive', 'Etag': '"957427698d04976bf1b9ea34e013f334"', 'X-Cache-Action': 'MISS', 'Cache-Control': 'max-age=30', 'Date': 'Thu, 07 Dec 2017 05:29:09 GMT', 'X-Cache-Age': '0'}
2017-12-06 23:29:19,252;zeus-log;INFO;writing found headers to log file
2017-12-06 23:29:19,253;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.bbc.co.uk-headers.json'
2017-12-06 23:29:19,253;zeus-log;INFO;searching a total of 5 pages of Gists for 'www.bbc.co.uk'
2017-12-06 23:29:19,254;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:29:19,983;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:29:20,507;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:29:21,073;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:29:21,609;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:29:22,134;zeus-log;DEBUG;found a total of 53 links to search
2017-12-06 23:29:22,743;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/x831617/3d434d22bad00b4aa6f89dd057006fe4/raw/6106e4bb52e6cf2e903851c2d5923f0465518852/gistfile1.txt'
2017-12-06 23:29:24,062;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/40536a74787c6c67119faa45220fe123/raw/5d6baf4c1a2f890bea59b1381a80bb662ff46931/brlog.trunk-test.20171207-142138'
2017-12-06 23:29:24,558;zeus-log;INFO;found match with given specifics ('bbc*'), saving Gist to file
2017-12-06 23:29:24,559;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/bbc-gist-match.log'
2017-12-06 23:29:25,952;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/499940e908907614cff8f076937be6c2/raw/42294004b447d32f843d6ebd11f5d89dc6a95489/brlog.trunk-test.20171207-143132'
2017-12-06 23:29:26,698;zeus-log;INFO;found match with given specifics ('bbc*'), saving Gist to file
2017-12-06 23:29:26,703;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/bbc(1).log'
2017-12-06 23:29:27,232;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/wynot/0889755e08ab42e2394f205aaa47c58e/raw/c3d39585aec8cc8caf7a990e49cacb3f5235b1e9/gistfile1.txt'
2017-12-06 23:29:28,880;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/bb98542f524d307378eb1327e23ceb6c/raw/80b9fbce9daa43d71a75187f62665db90b10c135/brlog.trunk-test.20171207-141639'
2017-12-06 23:29:29,296;zeus-log;INFO;found match with given specifics ('bbc*'), saving Gist to file
2017-12-06 23:29:29,301;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/gists/bbc(2).log'
2017-12-06 23:29:31,980;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/nitinware/e611ff7caf61ddf62c6652c359df83e1/raw/a9df894b278261c426ce889854ec719e3e2923f8/temperature.json'
2017-12-06 23:29:32,984;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/yambal/e3225e09e4ee682649d2e025f4326d21/raw/aacf3f072ab45fed5021ea3c0b413899e91b6214/QuickRelux_long.ssml'
2017-12-06 23:29:34,160;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/81b9e8b51b34f729b6957d96812dce6e/raw/775fb73394951aea5bf8c74e6b1089235c6a39d5/brlog.trunk-test.20171207-141653'
2017-12-06 23:29:35,392;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/9fdb2a59ae754ccafbfa60eb42f5e4d5/raw/52f8b3e0e8d2d90d70f2c5df8bad6d7fd49822e4/brlog.trunk-test.20171207-141404'
2017-12-06 23:29:37,414;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:29:37,570;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:29:37,570;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:29:37,571;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:29:37,572;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-07 13:20
duplicate of #256

**Closed** 2017-12-07 13:20 UTC
Labels: duplicate
