### ISSUE TITLE
Unhandled exception (RYQwDZf)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#325] opened 2017-12-28 15:40 UTC
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux32.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/root/zeus-scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/zeus-scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/root/zeus-scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```

Running details:
`Linux-4.4.50-v7+-armv7l-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py -d inurl:?pagenumber=2`

Log file info:
```2017-12-28 15:40:26,028;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-5.log'
2017-12-28 15:40:26,030;zeus-log;INFO;using default search engine
2017-12-28 15:40:26,031;zeus-log;INFO;starting dork scan with query 'inurl:?pagenumber=2'
2017-12-28 15:40:26,034;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)
2017-12-28 15:40:26,035;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
2017-12-28 15:40:26,036;zeus-log;INFO;attempting to gather query URL
2017-12-28 15:40:26,037;zeus-log;INFO;setting up virtual display to hide the browser
2017-12-28 15:40:26,267;zeus-log;INFO;setting the browser
2017-12-28 15:40:26,329;zeus-log;ERROR;[7;31;31mselenium_search.pyc failed to gather the URL from search engine, caught exception '[Errno 8] Exec format error' exception has been logged to current log file
Traceback (most recent call last):
  File "/root/zeus-scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/zeus-scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/root/zeus-scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

2017-12-28 15:40:38,575;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-28 15:40:38,576;zeus-log;INFO;[32mgetting authorization[0m
2017-12-28 15:40:38,579;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-28 15:40:38,580;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-28 19:04
Dupe of #319

**Closed by Ekultek** 2017-12-28 19:04 UTC
