### ISSUE TITLE
Message: 

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#82] opened 2017-10-12 22:18 UTC
Zeus version:
`1.0.39`

Error info:
```Traceback (most recent call last):
  File "/home/bush911/Desktop/Zeus-Scanner/var/google_search/search.py", line 248, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/bush911/Desktop/Zeus-Scanner/var/google_search/search.py", line 141, in get_urls
    retval = browser.current_url
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 563, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
UnexpectedAlertPresentException: Alert Text: None
Message: 
````

Running details:
`Linux-4.12.0-parrot6-686-pae-i686-with-Parrot-3.8-JollyRoger`

Commands used:
`zeus.py --dork-list=/home/bush911/Desktop/d0rks.txt --blackwidow=URL http://notebase.net/29216-video_98.html , -A --sqlmap-args=SQLMAP-ARGS sqlmaap`

Log file info:
```2017-10-12 22:44:26,052;zeus-log;INFO;log file being saved to '/home/bush911/Desktop/Zeus-Scanner/log/zeus-log-46.log'...
2017-10-12 22:44:26,053;zeus-log;WARNING;AOL will take a little longer due to pop-ups...
2017-10-12 22:44:26,053;zeus-log;INFO;specified to use non-default search engine...
2017-10-12 22:44:26,056;zeus-log;INFO;starting dork scan with query '# See LICENSE for license details.'...
2017-10-12 22:44:26,056;zeus-log;INFO;attempting to gather query URL...
2017-10-12 22:44:26,200;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 22:44:26,201;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 22:44:36,305;zeus-log;INFO;browser will open shortly...
2017-10-12 22:45:01,031;zeus-log;INFO;searching 'http://aol.com' using query '# See LICENSE for license details.'...
2017-10-12 22:45:05,018;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 22:45:05,095;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 22:45:05,095;zeus-log;INFO;no proxy configuration detected...
2017-10-12 22:45:06,603;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 22:45:06,611;zeus-log;INFO;found a total of 5 URL's with a GET parameter...
2017-10-12 22:45:06,612;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-7.log'...
2017-10-12 22:45:06,612;zeus-log;INFO;starting dork scan with query '# This file is part of v3n0m'...
2017-10-12 22:45:06,612;zeus-log;INFO;attempting to gather query URL...
2017-10-12 22:45:06,982;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 22:45:06,983;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 22:45:18,622;zeus-log;INFO;browser will open shortly...
2017-10-12 22:45:41,793;zeus-log;INFO;searching 'http://aol.com' using query '# This file is part of v3n0m'...
2017-10-12 22:45:45,771;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 22:45:45,881;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 22:45:45,882;zeus-log;INFO;no proxy configuration detected...
2017-10-12 22:45:47,268;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 22:45:47,275;zeus-log;INFO;found a total of 5 URL's with a GET parameter...
2017-10-12 22:45:47,276;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-8.log'...
2017-10-12 22:45:47,276;zeus-log;INFO;starting dork scan with query '********.asp?cid='...
2017-10-12 22:45:47,277;zeus-log;INFO;attempting to gather query URL...
2017-10-12 22:45:47,415;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 22:45:47,416;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 22:45:57,624;zeus-log;INFO;browser will open shortly...
2017-10-12 22:46:27,104;zeus-log;INFO;searching 'http://aol.com' using query '********.asp?cid='...
2017-10-12 22:46:31,036;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 22:46:31,114;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 22:46:31,115;zeus-log;INFO;no proxy configuration detected...
2017-10-12 22:46:32,655;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 22:46:32,662;zeus-log;INFO;found a total of 3 URL's with a GET parameter...
2017-10-12 22:46:32,663;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-9.log'...
2017-10-12 22:46:32,663;zeus-log;INFO;starting dork scan with query '********.php?cid='...
2017-10-12 22:46:32,663;zeus-log;INFO;attempting to gather query URL...
2017-10-12 22:46:32,804;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 22:46:32,805;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 22:46:45,596;zeus-log;INFO;browser will open shortly...
2017-10-12 22:47:10,125;zeus-log;INFO;searching 'http://aol.com' using query '********.php?cid='...
2017-10-12 22:47:13,983;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 22:47:14,076;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 22:47:14,076;zeus-log;INFO;no proxy configuration detected...
2017-10-12 22:47:15,738;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 22:47:15,744;zeus-log;INFO;found a total of 3 URL's with a GET parameter...
2017-10-12 22:47:15,745;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-10.log'...
2017-10-12 22:47:15,745;zeus-log;INFO;starting dork scan with query '********.php?id='...
2017-10-12 22:47:15,745;zeus-log;INFO;attempting to gather query URL...
2017-10-12 22:47:15,884;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 22:47:15,885;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 22:47:26,104;zeus-log;INFO;browser will open shortly...
2017-10-12 22:47:50,234;zeus-log;INFO;searching 'http://aol.com' using query '********.php?id='...
2017-10-12 22:47:54,519;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 22:47:54,619;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 22:47:54,619;zeus-log;INFO;no proxy configuration detected...
2017-10-12 22:47:56,195;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 22:47:56,200;zeus-log;INFO;found a total of 3 URL's with a GET parameter...
2017-10-12 22:47:56,201;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-11.log'...
2017-10-12 22:47:56,202;zeus-log;INFO;starting dork scan with query '********.php?pid='...
2017-10-12 22:47:56,202;zeus-log;INFO;attempting to gather query URL...
2017-10-12 22:47:56,350;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 22:47:56,350;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 22:48:10,139;zeus-log;INFO;browser will open shortly...
2017-10-12 22:48:38,724;zeus-log;INFO;searching 'http://aol.com' using query '********.php?pid='...
2017-10-12 22:48:42,613;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 22:48:42,703;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 22:48:42,703;zeus-log;INFO;no proxy configuration detected...
2017-10-12 22:48:44,163;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 22:48:44,169;zeus-log;INFO;found a total of 3 URL's with a GET parameter...
2017-10-12 22:48:44,170;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-12.log'...
2017-10-12 22:48:44,170;zeus-log;INFO;starting dork scan with query '********lang_englishlang_main_album.php?phpbb_root_path='...
2017-10-12 22:48:44,170;zeus-log;INFO;attempting to gather query URL...
2017-10-12 22:48:44,316;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 22:48:44,316;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 22:48:55,573;zeus-log;INFO;browser will open shortly...
2017-10-12 22:49:25,640;zeus-log;INFO;searching 'http://aol.com' using query '********lang_englishlang_main_album.php?phpbb_root_path='...
2017-10-12 22:49:30,357;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 22:49:30,484;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 22:49:30,484;zeus-log;INFO;no proxy configuration detected...
2017-10-12 22:49:31,948;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 22:49:31,954;zeus-log;INFO;found a total of 3 URL's with a GET parameter...
2017-10-12 22:49:31,955;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-13.log'...
2017-10-12 22:49:31,955;zeus-log;INFO;starting dork scan with query '********s_in_area.asp?area_id='...
2017-10-12 22:49:31,955;zeus-log;INFO;attempting to gather query URL...
2017-10-12 22:49:32,101;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 22:49:32,101;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 22:49:47,635;zeus-log;INFO;browser will open shortly...
2017-10-12 22:50:22,112;zeus-log;INFO;searching 'http://aol.com' using query '********s_in_area.asp?area_id='...
2017-10-12 22:50:26,373;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Alert Text: None
Message:' exception has been logged to current log file...
Traceback (most recent call last):
  File "/home/bush911/Desktop/Zeus-Scanner/var/google_search/search.py", line 248, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/bush911/Desktop/Zeus-Scanner/var/google_search/search.py", line 141, in get_urls
    retval = browser.current_url
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 563, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
UnexpectedAlertPresentException: Alert Text: None
Message: 


2017-10-12 23:18:07,295;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-12 23:18:07,296;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-12 23:18:07,297;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment] 2017-10-12 22:39
Didn't you literally just create a the same issue less then 30 minutes ago? duplicate of #81

**Closed by Ekultek** 2017-10-12 22:39 UTC
Labels: duplicate
