### ISSUE TITLE
Unhandled exception (tSOyOTG)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#317] opened 2017-12-22 18:36 UTC
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/android/Programas/Zeus-Scanner/lib/attacks/sqlmap_scan/__init__.py", line 222, in sqlmap_scan_main
    sqlmap_scan.show_sqlmap_log(api_id)
  File "/home/android/Programas/Zeus-Scanner/lib/attacks/sqlmap_scan/__init__.py", line 124, in show_sqlmap_log
    current_status = json.loads(requests.get(running_status_url).content)["status"]
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Running details:
`Linux-4.14.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py --random-agent --auto -s -b http://www.yatelollevo.com/?action=static.static&tpl=compra_online`

Log file info:
```2017-12-22 13:19:51,170;zeus-log;WARNING;please keep in mind that this is the API, output will not be saved to log file, it may take a little longer to finish processing, launching sqlmap
2017-12-22 13:26:16,497;zeus-log;INFO;currently running on 'http://www.yatelollevo.com/?action=donde_esta.donde_esta' (target #11)
2017-12-22 13:26:16,498;zeus-log;INFO;fetching target meta-data
2017-12-22 13:26:20,128;zeus-log;INFO;detecting target charset
2017-12-22 13:26:20,128;zeus-log;INFO;target charset appears to be 'iso-8859-1'
2017-12-22 13:26:20,128;zeus-log;INFO;attempting to get request headers for 'http://www.yatelollevo.com/?action=donde_esta.donde_esta'
2017-12-22 13:26:20,129;zeus-log;INFO;writing found headers to log file
2017-12-22 13:26:20,129;zeus-log;INFO;successfully wrote found items to '/home/android/Programas/Zeus-Scanner/log/header-log/www.yatelollevo.com(8).json'
2017-12-22 13:26:29,960;zeus-log;INFO;creating arguments for sqlmap
2017-12-22 13:26:29,977;zeus-log;INFO;attempting to launch sqlmap API
2017-12-22 13:26:29,985;zeus-log;INFO;sqlmap API is up and running, continuing process
2017-12-22 13:26:29,986;zeus-log;INFO;initializing new sqlmap scan with given URL 'http://www.yatelollevo.com/?action=donde_esta.donde_esta'
2017-12-22 13:26:29,991;zeus-log;INFO;gathering sqlmap API scan ID
2017-12-22 13:26:29,998;zeus-log;INFO;starting sqlmap scan on url: 'http://www.yatelollevo.com/?action=donde_esta.donde_esta'
2017-12-22 13:26:29,998;zeus-log;WARNING;please keep in mind that this is the API, output will not be saved to log file, it may take a little longer to finish processing, launching sqlmap
2017-12-22 13:29:41,852;zeus-log;ERROR;sqlmap API is not started, did you forget to start it? You will need to open a new terminal, cd into sqlmap, and run `python sqlmapapi.py -s` otherwise pass the correct flags to auto start the API
2017-12-22 13:29:41,853;zeus-log;INFO;currently running on 'http://www.yatelollevo.com/?action=static.static&tpl=compra_online' (target #12)
2017-12-22 13:29:41,853;zeus-log;INFO;fetching target meta-data
2017-12-22 13:29:49,436;zeus-log;INFO;detecting target charset
2017-12-22 13:29:49,436;zeus-log;INFO;target charset appears to be 'iso-8859-1'
2017-12-22 13:29:49,437;zeus-log;INFO;attempting to get request headers for 'http://www.yatelollevo.com/?action=static.static&tpl=compra_online'
2017-12-22 13:29:49,437;zeus-log;INFO;found a request cookie, saving to file
2017-12-22 13:29:49,437;zeus-log;INFO;successfully wrote found items to '/home/android/Programas/Zeus-Scanner/log/cookies/www.yatelollevo.com(5).log'
2017-12-22 13:29:49,438;zeus-log;INFO;writing found headers to log file
2017-12-22 13:29:49,438;zeus-log;INFO;successfully wrote found items to '/home/android/Programas/Zeus-Scanner/log/header-log/www.yatelollevo.com(9).json'
2017-12-22 13:30:01,820;zeus-log;INFO;creating arguments for sqlmap
2017-12-22 13:30:01,837;zeus-log;INFO;attempting to launch sqlmap API
2017-12-22 13:30:01,844;zeus-log;INFO;sqlmap API is up and running, continuing process
2017-12-22 13:30:01,844;zeus-log;INFO;initializing new sqlmap scan with given URL 'http://www.yatelollevo.com/?action=static.static&tpl=compra_online'
2017-12-22 13:30:01,849;zeus-log;INFO;gathering sqlmap API scan ID
2017-12-22 13:30:01,853;zeus-log;INFO;starting sqlmap scan on url: 'http://www.yatelollevo.com/?action=static.static&tpl=compra_online'
2017-12-22 13:30:01,853;zeus-log;WARNING;please keep in mind that this is the API, output will not be saved to log file, it may take a little longer to finish processing, launching sqlmap
2017-12-22 13:36:09,337;zeus-log;ERROR;[7;31;31mran into error 'No JSON object could be decoded', seems something went wrong, error has been saved to current log file.
Traceback (most recent call last):
  File "/home/android/Programas/Zeus-Scanner/lib/attacks/sqlmap_scan/__init__.py", line 222, in sqlmap_scan_main
    sqlmap_scan.show_sqlmap_log(api_id)
  File "/home/android/Programas/Zeus-Scanner/lib/attacks/sqlmap_scan/__init__.py", line 124, in show_sqlmap_log
    current_status = json.loads(requests.get(running_status_url).content)["status"]
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2017-12-22 13:36:30,541;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-22 13:36:30,541;zeus-log;INFO;[32mgetting authorization[0m
2017-12-22 13:36:30,542;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-22 13:36:30,542;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment] 2017-12-22 18:43
Start sqlmap API manually. This happens on my system as well when I try to autostart the API

**Comment by Ekultek** [comment] 2017-12-22 18:51
So the problem is this, depending on the system, when you launch the sqlmap start script it has a tendency to exit after starting. I haven’t been able to figure out a permanent fix for this yet. The workaround is to start the sqlmap API prior to launching, or when it prompts you. It seems that the API was launched successfully and started but something happened along the line to where it won’t connect. So just start it manually for now and I’ll figure out a fix for this in the near future

**Closed by Ekultek** 2017-12-22 18:51 UTC
Labels: support
