### ISSUE TITLE
Unhandled exception (hzvntDN)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#223] opened 2017-12-02 21:23 UTC
Zeus version:
`1.3.16.667610`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1023, in run_attacks
    github_gist_search_main(query, agent=agent, proxy=proxy, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 135, in github_gist_search_main
    gathered_links = get_raw_data(page_set, proxy=proxy, agent=agent, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 51, in get_raw_data
    gist_file = item["files"]
TypeError: string indices must be integers, not str
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d altamonte -g`

Log file info:
```2017-12-02 15:22:30,217;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-17.log'...
2017-12-02 15:22:30,217;zeus-log;INFO;using default search engine...
2017-12-02 15:22:30,218;zeus-log;INFO;starting dork scan with query 'altamonte'...
2017-12-02 15:22:30,219;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-12-02 15:22:30,219;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-12-02 15:22:30,219;zeus-log;INFO;attempting to gather query URL...
2017-12-02 15:22:30,220;zeus-log;INFO;setting up virtual display to hide the browser...
2017-12-02 15:22:30,380;zeus-log;INFO;setting the browser...
2017-12-02 15:22:39,372;zeus-log;INFO;browser will open shortly...
2017-12-02 15:22:40,518;zeus-log;INFO;searching search engine using query 'http://google.com'...
2017-12-02 15:22:43,628;zeus-log;INFO;closing the browser and continuing process..
2017-12-02 15:22:43,734;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-12-02 15:22:43,735;zeus-log;INFO;no proxy configuration detected...
2017-12-02 15:22:44,628;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.3.16.667610 (Language=Python/2.7.13; Platform=Linux)'...
2017-12-02 15:22:44,647;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-8.log'...
2017-12-02 15:22:44,647;zeus-log;INFO;found a total of 43 URLs with given query 'altamonte'...
2017-12-02 15:22:44,647;zeus-log;INFO;currently running on 'https://www.tripadvisor.com/Hotels-g29161-Altamonte_Springs_Florida-Hotels.html+altamonte' (target #1)...
2017-12-02 15:22:44,647;zeus-log;INFO;checking for HTTP headers...
2017-12-02 15:22:44,648;zeus-log;INFO;checking if target URL is protected by some kind of WAF/IPS/IDS...
2017-12-02 15:23:04,547;zeus-log;INFO;no WAF/IDS/IPS has been identified on target URL...
2017-12-02 15:23:04,550;zeus-log;INFO;attempting to get request headers for 'https://www.tripadvisor.com/Hotels-g29161-Altamonte_Springs_Florida-Hotels.html+altamonte'...
2017-12-02 15:23:05,352;zeus-log;INFO;found a request cookie, saving to file...
2017-12-02 15:23:05,353;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.tripadvisor.com(2).log'...
2017-12-02 15:23:05,354;zeus-log;INFO;writing found headers to log file...
2017-12-02 15:23:05,355;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.tripadvisor.com(2).json'...
2017-12-02 15:23:09,347;zeus-log;WARNING;you have 55 unauthenticated requests remaining...
2017-12-02 15:23:09,349;zeus-log;INFO;searching Github Gists for 'www.tripadvisor.com'...
2017-12-02 15:23:09,349;zeus-log;INFO;searching a total of 5 pages of Gists...
2017-12-02 15:23:10,166;zeus-log;ERROR;[7;31;31mran into exception 'string indices must be integers, not str' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1023, in run_attacks
    github_gist_search_main(query, agent=agent, proxy=proxy, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 135, in github_gist_search_main
    gathered_links = get_raw_data(page_set, proxy=proxy, agent=agent, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 51, in get_raw_data
    gist_file = item["files"]
TypeError: string indices must be integers, not str

2017-12-02 15:23:10,430;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-02 15:23:10,430;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-02 15:23:10,431;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-02 15:23:10,431;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-12-02 23:42
Dupe of #221

**Closed by Ekultek** 2017-12-02 23:42 UTC
Labels: duplicate
