### ISSUE TITLE
Unhandled exception (ujyHqAS)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#222] opened 2017-12-02 21:21 UTC
Zeus version:
`1.3.16.667610`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1023, in run_attacks
    github_gist_search_main(query, agent=agent, proxy=proxy, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 139, in github_gist_search_main
    gathered_links = get_raw_data(page_set, proxy=proxy, agent=agent, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 49, in get_raw_data
    print data["raw_url"]
TypeError: string indices must be integers, not str
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d altamonte -g`

Log file info:
```2017-12-02 15:20:51,103;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-16.log'...
2017-12-02 15:20:51,103;zeus-log;INFO;using default search engine...
2017-12-02 15:20:51,103;zeus-log;INFO;starting dork scan with query 'altamonte'...
2017-12-02 15:20:51,121;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-12-02 15:20:51,122;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-12-02 15:20:51,122;zeus-log;INFO;attempting to gather query URL...
2017-12-02 15:20:51,122;zeus-log;INFO;setting up virtual display to hide the browser...
2017-12-02 15:20:51,485;zeus-log;INFO;setting the browser...
2017-12-02 15:20:59,560;zeus-log;INFO;browser will open shortly...
2017-12-02 15:21:01,122;zeus-log;INFO;searching search engine using query 'http://google.com'...
2017-12-02 15:21:04,220;zeus-log;INFO;closing the browser and continuing process..
2017-12-02 15:21:04,358;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-12-02 15:21:04,359;zeus-log;INFO;no proxy configuration detected...
2017-12-02 15:21:05,112;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.3.16.667610 (Language=Python/2.7.13; Platform=Linux)'...
2017-12-02 15:21:05,136;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-7.log'...
2017-12-02 15:21:05,136;zeus-log;INFO;found a total of 43 URLs with given query 'altamonte'...
2017-12-02 15:21:05,138;zeus-log;INFO;currently running on 'https://www.tripadvisor.com/Hotels-g29161-Altamonte_Springs_Florida-Hotels.html+altamonte' (target #1)...
2017-12-02 15:21:05,139;zeus-log;INFO;checking for HTTP headers...
2017-12-02 15:21:05,139;zeus-log;INFO;checking if target URL is protected by some kind of WAF/IPS/IDS...
2017-12-02 15:21:25,724;zeus-log;INFO;no WAF/IDS/IPS has been identified on target URL...
2017-12-02 15:21:25,787;zeus-log;INFO;attempting to get request headers for 'https://www.tripadvisor.com/Hotels-g29161-Altamonte_Springs_Florida-Hotels.html+altamonte'...
2017-12-02 15:21:26,787;zeus-log;INFO;found a request cookie, saving to file...
2017-12-02 15:21:26,789;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.tripadvisor.com(1).log'...
2017-12-02 15:21:26,790;zeus-log;INFO;writing found headers to log file...
2017-12-02 15:21:26,791;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.tripadvisor.com(1).json'...
2017-12-02 15:21:41,240;zeus-log;WARNING;you have 57 unauthenticated requests remaining...
2017-12-02 15:21:41,241;zeus-log;INFO;searching Github Gists for 'www.tripadvisor.com'...
2017-12-02 15:21:41,241;zeus-log;INFO;searching a total of 5 pages of Gists...
2017-12-02 15:21:42,356;zeus-log;ERROR;[7;31;31mran into exception 'string indices must be integers, not str' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1023, in run_attacks
    github_gist_search_main(query, agent=agent, proxy=proxy, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 139, in github_gist_search_main
    gathered_links = get_raw_data(page_set, proxy=proxy, agent=agent, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 49, in get_raw_data
    print data["raw_url"]
TypeError: string indices must be integers, not str

2017-12-02 15:21:42,637;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-02 15:21:42,637;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-02 15:21:42,638;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-02 15:21:42,638;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment] 2017-12-02 23:41
Duplicate of #221

**Closed by Ekultek** 2017-12-02 23:41 UTC
Labels: duplicate
